// Generated from scripts/locales/results.tsv.
export const copy = {
  "da": {
    "loading": "Vi undersøger hjemmesiden og dens adgangsregler …",
    "unavailable": "Analysetjenesten er ikke tilgængelig på denne visning. Prøv igen senere.",
    "queue": "Der er kø ved tjekket. Vent tre minutter og prøv igen.",
    "failed": "Tjekket kunne ikke gennemføres. Kontrollér webadressen, eller prøv igen senere. Private adresser understøttes ikke.",
    "timeout": "Tjekket tog for lang tid. Prøv igen senere.",
    "ready": "Førstetjekket er klar.",
    "coverage": "Datadækning: {coverage} % af den fulde model. Risikoen gælder kun de målte dele.",
    "clarify": "Få afklaret: {label}.",
    "presenceAction": "Undersøg faktiske AI-svar på relevante kundespørgsmål.",
    "confirmedCount": "{passed} af {total} signaler bekræftet.",
    "someUnknown": "Nogle forhold kunne ikke måles.",
    "seeFindings": "Se fundene nedenfor for forklaring og næste skridt.",
    "found": "findes i sidens tekst",
    "notFound": "ikke fundet i den undersøgte tekst",
    "unknown": "Ikke målt",
    "confirmed": "Bekræftet",
    "review": "Se nærmere",
    "preliminary": "Foreløbig",
    "Low": "Low",
    "Medium": "Medium",
    "High": "High",
    "summary": "Et første billede af hjemmesidens tilgængelighed og tydelighed. Scoren dokumenterer ikke, om AI anbefaler virksomheden.",
    "perceptionMatch": "Indledende tekstmatch",
    "perceptionMissing": "Mangler ønsket billede",
    "perceptionNote": "Ordmatch er et samtalegrundlag, ikke en vurdering af kundernes faktiske opfattelse. En fuld vurdering kræver virksomhedens mål og en kvalitativ gennemgang.",
    "limit1": "Kun den indtastede side, adgangsregler og én sideoversigt undersøges.",
    "limit2": "Tilladelse i adgangsregler dokumenterer ikke faktisk adgang gennem firewall eller placering i søgeresultater.",
    "limit3": "Forståelse vurderes via enkle signaler; tekst og virksomhedsdata kan være ufuldstændige eller forældede.",
    "limit4": "AI Presence udgør 30 % af den fulde model og er endnu ikke målt. Manglende målinger tæller ikke som nul.",
    "q1": "Hvilke virksomheder kan hjælpe med {offering} i {market}?",
    "q2": "Hvem vil du anbefale til {offering} for {market}, og hvorfor?",
    "q3": "Hvilke alternativer er der til {company}?",
    "offering": "[ydelse]",
    "market": "[område/målgruppe]",
    "company": "[virksomheden]",
    "method": "Brug POST.",
    "large": "Indtastningen er for lang.",
    "blocked": "Hjemmesidens adgangsregler tillader ikke vores tjek af denne side.",
    "notHtml": "Siden kunne ikke læses som en almindelig hjemmeside. Prøv forsiden.",
    "readable.label": "Indhold kan læses",
    "readable.action": "Gør virksomhedens vigtigste indhold læsbart uden interaktion.",
    "readable.evidence": "{count} ord i den hentede side.",
    "crawlers.label": "Adgang for søgetjenester",
    "crawlers.action": "Gennemgå adgangsreglerne for søgetjenester. Et bevidst fravalg kan være korrekt.",
    "crawlers.unknown": "Adgangsregler kunne ikke verificeres.",
    "allowed": "tilladt",
    "restricted": "begrænset",
    "indexable.label": "Siden må vises i søgeresultater",
    "indexable.action": "Undersøg, om udelukkelsen fra søgeresultater er tilsigtet.",
    "indexable.yes": "Ingen noindex-regel fundet i den hentede side eller svarheader.",
    "indexable.no": "Der er fundet en regel, som begrænser indeksering.",
    "sitemap.label": "Oversigt over hjemmesidens sider",
    "sitemap.action": "Tilføj en opdateret sideoversigt, og henvis til den fra hjemmesidens adgangsregler.",
    "sitemap.yes": "En XML-sideoversigt blev fundet.",
    "sitemap.no": "Ingen gyldig sideoversigt på den undersøgte adresse.",
    "sitemap.unknown": "Sideoversigten kunne ikke kontrolleres.",
    "identity.label": "Virksomheden er identificeret",
    "identity.action": "Skriv virksomhedens navn tydeligt, og forbind det med en entydig virksomhedsprofil.",
    "identity.no": "Intet verificeret virksomhedsnavn fundet i de undersøgte signaler.",
    "identity.text": "Virksomhedsnavnet “{company}” findes i sidens tekst.",
    "offering.label": "Tilbuddet er beskrevet",
    "offering.action": "Beskriv konkret, hvad I tilbyder, og hvem det hjælper.",
    "offering.no": "Ingen kort sidebeskrivelse fundet.",
    "market.label": "Geografi eller målgruppe er angivet",
    "market.action": "Angiv tydeligt jeres område og målgruppe på relevante sider.",
    "market.address": "Adresse fundet i virksomhedsdata.",
    "market.audience": "Område eller målgruppe fundet i virksomhedsdata.",
    "market.search": "Søgt efter “{market}” i sidens tekst.",
    "market.no": "Geografi/målgruppe ikke verificeret.",
    "entity.label": "Sammenhængende virksomhedsprofil",
    "entity.action": "Knyt navn, webadresse og kontaktoplysninger sammen i hjemmesidens virksomhedsdata.",
    "entity.yes": "Virksomhedsdata fundet; navn, identitet og kontakt kontrolleret.",
    "entity.no": "Ingen genkendelig virksomhedsprofil i strukturerede data.",
    "sourceNote": "Uddrag fra hjemmesiden vises på originalsproget.",
    "fetchLarge": "Vi kunne ikke hente hjemmesiden teknisk, fordi siden er meget stor. Det betyder ikke nødvendigvis, at AI ikke kan finde virksomheden. Store webshops kan kræve en dybere analyse.",
    "fetchTimeout": "Vi kunne ikke hente hjemmesiden teknisk inden for tidsgrænsen. Det betyder ikke nødvendigvis, at AI ikke kan finde virksomheden. Siden kan være langsom eller kræve en anden hentemetode.",
    "fetchBlocked": "Hjemmesiden ser ud til at afvise vores automatiske serverkald. Det betyder ikke nødvendigvis, at ChatGPT eller søgemaskiner ikke kan finde virksomheden.",
    "fetchPrivate": "Adressen kunne ikke kontrolleres som en offentlig hjemmeside. Private adresser, interne netværk og særlige porte understøttes ikke.",
    "fetchDns": "Domænet kunne ikke slås op lige nu. Kontrollér webadressen, eller prøv igen senere.",
    "fetchFailed": "Vi kunne ikke hente hjemmesiden teknisk. Det betyder ikke nødvendigvis, at AI ikke kan finde virksomheden. Siden kan blokere automatiske kald, være meget tung, eller kræve en anden hentemetode."
  },
  "nb": {
    "loading": "Vi undersøker nettsiden og tilgangsreglene …",
    "unavailable": "Analysetjenesten er ikke tilgjengelig i denne visningen. Prøv igjen senere.",
    "queue": "Det er kø. Vent tre minutter og prøv igjen.",
    "failed": "Testen kunne ikke gjennomføres. Kontroller nettadressen eller prøv igjen senere. Private adresser støttes ikke.",
    "timeout": "Testen tok for lang tid. Prøv igjen senere.",
    "ready": "Førstesjekken er klar.",
    "coverage": "Datadekning: {coverage} % av den fulle modellen. Risikoen gjelder bare de målte delene.",
    "clarify": "Få avklart: {label}.",
    "presenceAction": "Undersøk faktiske AI-svar på relevante kundespørsmål.",
    "confirmedCount": "{passed} av {total} signaler bekreftet.",
    "someUnknown": "Noen forhold kunne ikke måles.",
    "seeFindings": "Se funnene nedenfor for forklaring og neste skritt.",
    "found": "finnes i sidens tekst",
    "notFound": "ikke funnet i den undersøkte teksten",
    "unknown": "Ikke målt",
    "confirmed": "Bekreftet",
    "review": "Se nærmere",
    "preliminary": "Foreløpig",
    "Low": "Lav",
    "Medium": "Middels",
    "High": "Høy",
    "summary": "Et første bilde av nettsidens tilgjengelighet og tydelighet. Poengsummen dokumenterer ikke om AI anbefaler virksomheten.",
    "perceptionMatch": "Innledende tekstsammenligning",
    "perceptionMissing": "Mangler ønsket bilde",
    "perceptionNote": "Ordtreff er et samtalegrunnlag, ikke en vurdering av kundenes faktiske oppfatning. En full vurdering krever virksomhetens mål og en kvalitativ gjennomgang.",
    "limit1": "Bare den angitte siden, tilgangsreglene og én sideoversikt undersøkes.",
    "limit2": "Tillatelse i tilgangsreglene dokumenterer ikke faktisk tilgang gjennom brannmur eller plassering i søkeresultater.",
    "limit3": "Forståelse vurderes gjennom enkle signaler; tekst og virksomhetsdata kan være ufullstendige eller utdaterte.",
    "limit4": "AI Presence utgjør 30 % av den fulle modellen og er ennå ikke målt. Manglende målinger teller ikke som null.",
    "q1": "Hvilke virksomheter kan hjelpe med {offering} i {market}?",
    "q2": "Hvem vil du anbefale til {offering} for {market}, og hvorfor?",
    "q3": "Hvilke alternativer finnes til {company}?",
    "offering": "[tjeneste]",
    "market": "[område/målgruppe]",
    "company": "[virksomheten]",
    "method": "Bruk POST.",
    "large": "Inntastingen er for lang.",
    "blocked": "Nettsidens tilgangsregler tillater ikke vår test av denne siden.",
    "notHtml": "Siden kunne ikke leses som en vanlig nettside. Prøv forsiden.",
    "readable.label": "Innholdet kan leses",
    "readable.action": "Gjør virksomhetens viktigste innhold lesbart uten interaksjon.",
    "readable.evidence": "{count} ord på den hentede siden.",
    "crawlers.label": "Tilgang for søketjenester",
    "crawlers.action": "Gå gjennom tilgangsreglene for søketjenester. Et bevisst fravalg kan være riktig.",
    "crawlers.unknown": "Tilgangsreglene kunne ikke verifiseres.",
    "allowed": "tillatt",
    "restricted": "begrenset",
    "indexable.label": "Siden kan vises i søkeresultater",
    "indexable.action": "Undersøk om utelukkelsen fra søkeresultater er tilsiktet.",
    "indexable.yes": "Ingen noindex-regel funnet på den hentede siden eller i svarheaderen.",
    "indexable.no": "Det er funnet en regel som begrenser indeksering.",
    "sitemap.label": "Oversikt over nettstedets sider",
    "sitemap.action": "Legg til en oppdatert sideoversikt og henvis til den fra nettstedets tilgangsregler.",
    "sitemap.yes": "En XML-sideoversikt ble funnet.",
    "sitemap.no": "Ingen gyldig sideoversikt på den undersøkte adressen.",
    "sitemap.unknown": "Sideoversikten kunne ikke kontrolleres.",
    "identity.label": "Virksomheten er identifisert",
    "identity.action": "Skriv virksomhetens navn tydelig og knytt det til en entydig virksomhetsprofil.",
    "identity.no": "Ingen verifisert virksomhetsidentitet funnet i de undersøkte signalene.",
    "identity.text": "Virksomhetsnavnet «{company}» finnes i sidens tekst.",
    "offering.label": "Tilbudet er beskrevet",
    "offering.action": "Beskriv konkret hva dere tilbyr og hvem det hjelper.",
    "offering.no": "Ingen kort sidebeskrivelse funnet.",
    "market.label": "Geografi eller målgruppe er angitt",
    "market.action": "Oppgi tydelig området og målgruppen deres på relevante sider.",
    "market.address": "Adresse funnet i virksomhetsdata.",
    "market.audience": "Område eller målgruppe funnet i virksomhetsdata.",
    "market.search": "Søkt etter «{market}» i sidens tekst.",
    "market.no": "Geografi/målgruppe ikke verifisert.",
    "entity.label": "Sammenhengende virksomhetsprofil",
    "entity.action": "Knytt navn, nettadresse og kontaktinformasjon sammen i nettstedets virksomhetsdata.",
    "entity.yes": "Virksomhetsdata funnet; navn, identitet og kontakt kontrollert.",
    "entity.no": "Ingen gjenkjennelig virksomhetsprofil i strukturerte data.",
    "sourceNote": "Utdrag fra nettsiden vises på originalspråket.",
    "fetchLarge": "Vi kunne ikke hente nettsiden fordi den er svært stor. Dette betyr ikke nødvendigvis at AI ikke kan finne virksomheten. Store nettbutikker kan kreve en grundigere analyse.",
    "fetchTimeout": "Vi kunne ikke hente nettsiden innen tidsfristen. Dette betyr ikke nødvendigvis at AI ikke kan finne virksomheten. Siden kan være treg eller kreve en annen hentemetode.",
    "fetchBlocked": "Nettsiden ser ut til å avvise våre automatiske forespørsler. Dette betyr ikke nødvendigvis at ChatGPT eller søkemotorer ikke kan finne virksomheten.",
    "fetchPrivate": "Adressen kunne ikke bekreftes som en offentlig nettside. Private adresser, interne nettverk og spesielle porter støttes ikke.",
    "fetchDns": "Domenet kunne ikke slås opp akkurat nå. Kontroller nettadressen, eller prøv igjen senere.",
    "fetchFailed": "Vi kunne ikke hente nettsiden teknisk. Dette betyr ikke nødvendigvis at AI ikke kan finne virksomheten. Siden kan blokkere automatiske forespørsler, være svært stor eller kreve en annen hentemetode."
  },
  "en": {
    "loading": "We are checking the website and its access rules …",
    "unavailable": "The analysis service is unavailable in this view. Please try again later.",
    "queue": "The check is busy. Wait three minutes and try again.",
    "failed": "The check could not be completed. Check the website address or try again later. Private addresses are not supported.",
    "timeout": "The check timed out. Please try again later.",
    "ready": "Your initial check is ready.",
    "coverage": "Data coverage: {coverage}% of the full model. Risk applies only to the measured parts.",
    "clarify": "Clarify: {label}.",
    "presenceAction": "Examine actual AI responses to relevant customer questions.",
    "confirmedCount": "{passed} of {total} signals confirmed.",
    "someUnknown": "Some items could not be measured.",
    "seeFindings": "See the findings below for explanations and next steps.",
    "found": "found in the page text",
    "notFound": "not found in the text examined",
    "unknown": "Not measured",
    "confirmed": "Confirmed",
    "review": "Review",
    "preliminary": "Preliminary",
    "Low": "Low",
    "Medium": "Medium",
    "High": "High",
    "summary": "An initial view of the website’s accessibility and clarity. The score does not establish whether AI recommends the business.",
    "perceptionMatch": "Initial text comparison",
    "perceptionMissing": "Desired perception not provided",
    "perceptionNote": "Word matches are a starting point for discussion, not a measure of actual customer perception. A full assessment requires business goals and a qualitative review.",
    "limit1": "Only the submitted page, access rules and one sitemap are examined.",
    "limit2": "Permission in access rules does not establish actual access through a firewall or placement in search results.",
    "limit3": "Understanding is assessed using simple signals; text and business data may be incomplete or outdated.",
    "limit4": "AI Presence accounts for 30% of the full model and has not yet been measured. Missing measurements do not count as zero.",
    "q1": "Which businesses can help with {offering} in {market}?",
    "q2": "Who would you recommend for {offering} for {market}, and why?",
    "q3": "What alternatives are there to {company}?",
    "offering": "[service]",
    "market": "[area/audience]",
    "company": "[business]",
    "method": "Use POST.",
    "large": "The input is too long.",
    "blocked": "The website’s access rules do not allow us to check this page.",
    "notHtml": "The page could not be read as a standard web page. Try the homepage.",
    "readable.label": "Content can be read",
    "readable.action": "Make the business’s key content readable without interaction.",
    "readable.evidence": "{count} words in the retrieved page.",
    "crawlers.label": "Access for search services",
    "crawlers.action": "Review access rules for search services. An intentional restriction may be appropriate.",
    "crawlers.unknown": "Access rules could not be verified.",
    "allowed": "allowed",
    "restricted": "restricted",
    "indexable.label": "Page permitted in search results",
    "indexable.action": "Check whether exclusion from search results is intentional.",
    "indexable.yes": "No noindex rule found in the retrieved page or response header.",
    "indexable.no": "A rule restricting indexing was found.",
    "sitemap.label": "Index of website pages",
    "sitemap.action": "Add an up-to-date sitemap and reference it in the website’s access rules.",
    "sitemap.yes": "An XML sitemap was found.",
    "sitemap.no": "No valid sitemap at the address checked.",
    "sitemap.unknown": "The sitemap could not be checked.",
    "identity.label": "Business identity found",
    "identity.action": "State the business name clearly and link it to an unambiguous business profile.",
    "identity.no": "No verified business name found in the signals examined.",
    "identity.text": "The business name “{company}” appears in the page text.",
    "offering.label": "Offering described",
    "offering.action": "Describe specifically what you offer and who it helps.",
    "offering.no": "No short page description found.",
    "market.label": "Location or audience specified",
    "market.action": "Clearly state your area and audience on relevant pages.",
    "market.address": "Address found in business data.",
    "market.audience": "Area or audience found in business data.",
    "market.search": "Searched for “{market}” in the page text.",
    "market.no": "Location/audience not verified.",
    "entity.label": "Connected business profile",
    "entity.action": "Connect the name, website address and contact details in the website’s business data.",
    "entity.yes": "Business data found; name, identity and contact checked.",
    "entity.no": "No recognisable business profile in structured data.",
    "sourceNote": "Website excerpts are shown in their original language.",
    "fetchLarge": "We could not retrieve the website because it is very large. This does not necessarily mean AI cannot find the business. Large online stores may require a deeper analysis.",
    "fetchTimeout": "We could not retrieve the website within the time limit. This does not necessarily mean AI cannot find the business. The site may be slow or require a different retrieval method.",
    "fetchBlocked": "The website appears to reject our automated requests. This does not necessarily mean ChatGPT or search engines cannot find the business.",
    "fetchPrivate": "The address could not be verified as a public website. Private addresses, internal networks and non-standard ports are not supported.",
    "fetchDns": "The domain could not be resolved right now. Check the web address or try again later.",
    "fetchFailed": "We could not technically retrieve the website. This does not necessarily mean AI cannot find the business. The site may block automated requests, be very large or require a different retrieval method."
  },
  "de": {
    "loading": "Wir prüfen die Website und ihre Zugangsregeln …",
    "unavailable": "Der Analysedienst ist in dieser Ansicht nicht verfügbar. Bitte versuchen Sie es später erneut.",
    "queue": "Der Check ist ausgelastet. Warten Sie drei Minuten und versuchen Sie es erneut.",
    "failed": "Der Check konnte nicht abgeschlossen werden. Prüfen Sie die Webadresse oder versuchen Sie es später erneut. Private Adressen werden nicht unterstützt.",
    "timeout": "Der Check hat zu lange gedauert. Bitte versuchen Sie es später erneut.",
    "ready": "Ihr Erstcheck ist fertig.",
    "coverage": "Datenabdeckung: {coverage} % des vollständigen Modells. Das Risiko bezieht sich nur auf die gemessenen Teile.",
    "clarify": "Klären Sie: {label}.",
    "presenceAction": "Untersuchen Sie tatsächliche KI-Antworten auf relevante Kundenfragen.",
    "confirmedCount": "{passed} von {total} Signalen bestätigt.",
    "someUnknown": "Einige Aspekte konnten nicht gemessen werden.",
    "seeFindings": "Erläuterungen und nächste Schritte finden Sie in den Ergebnissen unten.",
    "found": "im Seitentext gefunden",
    "notFound": "im untersuchten Text nicht gefunden",
    "unknown": "Nicht gemessen",
    "confirmed": "Bestätigt",
    "review": "Näher prüfen",
    "preliminary": "Vorläufig",
    "Low": "Niedrig",
    "Medium": "Mittel",
    "High": "Hoch",
    "summary": "Ein erster Eindruck von Zugänglichkeit und Klarheit der Website. Die Bewertung belegt nicht, ob KI das Unternehmen empfiehlt.",
    "perceptionMatch": "Erster Textabgleich",
    "perceptionMissing": "Gewünschtes Bild nicht angegeben",
    "perceptionNote": "Worttreffer sind eine Gesprächsgrundlage, keine Bewertung der tatsächlichen Kundenwahrnehmung. Eine vollständige Bewertung erfordert Unternehmensziele und eine qualitative Prüfung.",
    "limit1": "Es werden nur die angegebene Seite, die Zugangsregeln und eine Sitemap untersucht.",
    "limit2": "Eine Erlaubnis in den Zugangsregeln belegt weder tatsächlichen Zugriff durch eine Firewall noch eine Platzierung in Suchergebnissen.",
    "limit3": "Verständlichkeit wird anhand einfacher Signale bewertet; Texte und Unternehmensdaten können unvollständig oder veraltet sein.",
    "limit4": "KI-Präsenz macht 30 % des vollständigen Modells aus und wurde noch nicht gemessen. Fehlende Messungen zählen nicht als null.",
    "q1": "Welche Unternehmen können bei {offering} in {market} helfen?",
    "q2": "Wen würden Sie für {offering} für {market} empfehlen und warum?",
    "q3": "Welche Alternativen gibt es zu {company}?",
    "offering": "[Leistung]",
    "market": "[Region/Zielgruppe]",
    "company": "[Unternehmen]",
    "method": "Verwenden Sie POST.",
    "large": "Die Eingabe ist zu lang.",
    "blocked": "Die Zugangsregeln der Website erlauben unseren Check dieser Seite nicht.",
    "notHtml": "Die Seite konnte nicht als normale Webseite gelesen werden. Versuchen Sie die Startseite.",
    "readable.label": "Inhalte sind lesbar",
    "readable.action": "Machen Sie die wichtigsten Unternehmensinhalte ohne Interaktion lesbar.",
    "readable.evidence": "{count} Wörter auf der abgerufenen Seite.",
    "crawlers.label": "Zugang für Suchdienste",
    "crawlers.action": "Prüfen Sie die Zugangsregeln für Suchdienste. Eine bewusste Einschränkung kann richtig sein.",
    "crawlers.unknown": "Die Zugangsregeln konnten nicht überprüft werden.",
    "allowed": "erlaubt",
    "restricted": "eingeschränkt",
    "indexable.label": "Anzeige in Suchergebnissen zulässig",
    "indexable.action": "Prüfen Sie, ob der Ausschluss aus Suchergebnissen beabsichtigt ist.",
    "indexable.yes": "Keine noindex-Regel auf der abgerufenen Seite oder im Antwortheader gefunden.",
    "indexable.no": "Eine Regel zur Einschränkung der Indexierung wurde gefunden.",
    "sitemap.label": "Übersicht der Website-Seiten",
    "sitemap.action": "Erstellen Sie eine aktuelle Sitemap und verweisen Sie in den Zugangsregeln darauf.",
    "sitemap.yes": "Eine XML-Sitemap wurde gefunden.",
    "sitemap.no": "Keine gültige Sitemap unter der untersuchten Adresse.",
    "sitemap.unknown": "Die Sitemap konnte nicht geprüft werden.",
    "identity.label": "Unternehmen identifiziert",
    "identity.action": "Geben Sie den Unternehmensnamen klar an und verbinden Sie ihn mit einem eindeutigen Unternehmensprofil.",
    "identity.no": "Kein bestätigter Unternehmensname in den untersuchten Signalen gefunden.",
    "identity.text": "Der Unternehmensname „{company}“ erscheint im Seitentext.",
    "offering.label": "Angebot beschrieben",
    "offering.action": "Beschreiben Sie konkret, was Sie anbieten und wem es hilft.",
    "offering.no": "Keine kurze Seitenbeschreibung gefunden.",
    "market.label": "Region oder Zielgruppe angegeben",
    "market.action": "Geben Sie Ihre Region und Zielgruppe auf relevanten Seiten klar an.",
    "market.address": "Adresse in den Unternehmensdaten gefunden.",
    "market.audience": "Region oder Zielgruppe in den Unternehmensdaten gefunden.",
    "market.search": "Im Seitentext nach „{market}“ gesucht.",
    "market.no": "Region/Zielgruppe nicht bestätigt.",
    "entity.label": "Zusammenhängendes Unternehmensprofil",
    "entity.action": "Verknüpfen Sie Name, Webadresse und Kontaktdaten in den Unternehmensdaten Ihrer Website.",
    "entity.yes": "Unternehmensdaten gefunden; Name, Identität und Kontakt geprüft.",
    "entity.no": "Kein erkennbares Unternehmensprofil in strukturierten Daten.",
    "sourceNote": "Website-Auszüge werden in der Originalsprache angezeigt.",
    "fetchLarge": "Die Website konnte wegen ihrer Größe nicht abgerufen werden. Das bedeutet nicht zwangsläufig, dass KI das Unternehmen nicht finden kann. Große Onlineshops können eine vertiefte Analyse erfordern.",
    "fetchTimeout": "Die Website konnte nicht innerhalb des Zeitlimits abgerufen werden. Das bedeutet nicht zwangsläufig, dass KI das Unternehmen nicht finden kann. Die Seite ist möglicherweise langsam oder erfordert eine andere Abrufmethode.",
    "fetchBlocked": "Die Website scheint unsere automatisierten Anfragen abzulehnen. Das bedeutet nicht zwangsläufig, dass ChatGPT oder Suchmaschinen das Unternehmen nicht finden können.",
    "fetchPrivate": "Die Adresse konnte nicht als öffentliche Website bestätigt werden. Private Adressen, interne Netzwerke und besondere Ports werden nicht unterstützt.",
    "fetchDns": "Die Domain konnte gerade nicht aufgelöst werden. Prüfen Sie die Webadresse oder versuchen Sie es später erneut.",
    "fetchFailed": "Die Website konnte technisch nicht abgerufen werden. Das bedeutet nicht zwangsläufig, dass KI das Unternehmen nicht finden kann. Die Seite blockiert möglicherweise automatisierte Anfragen, ist sehr groß oder erfordert eine andere Abrufmethode."
  }
};
export function language(value) { return ({dk:'da',no:'nb',da:'da',nb:'nb',en:'en',de:'de'})[value] || 'da'; }
export function translator(locale) {
 const messages=copy[language(locale)];
 return (key,values={}) => (messages[key] || copy.da[key] || key).replace(/\{(\w+)\}/g,(_,name)=>String(values[name] ?? ''));
}
