// Generated from scripts/locales/results.tsv.
export const copy = {
  "da": {
    "loading": "Vi undersøger hjemmesiden og dens adgangsregler …",
    "unavailable": "Analysetjenesten er ikke tilgængelig på denne visning. Prøv igen senere.",
    "queue": "Der er kø ved tjekket. Vent tre minutter og prøv igen.",
    "failed": "Tjekket kunne ikke gennemføres. Kontrollér webadressen, eller prøv igen senere. Private adresser understøttes ikke.",
    "timeout": "Tjekket tog for lang tid. Prøv igen senere.",
    "ready": "Førstetjekket er klar.",
    "coverage": "Datadækning: {coverage} % af den fulde model. Risikoen gælder kun de målte dele.",
    "clarify": "Få afklaret: {label}.",
    "presenceAction": "Undersøg faktiske AI-svar på relevante kundespørgsmål.",
    "confirmedCount": "{passed} af {total} signaler bekræftet.",
    "someUnknown": "Nogle forhold kunne ikke måles.",
    "seeFindings": "Se fundene nedenfor for forklaring og næste skridt.",
    "found": "findes i sidens tekst",
    "notFound": "ikke fundet i den undersøgte tekst",
    "unknown": "Ikke målt",
    "confirmed": "Bekræftet",
    "review": "Se nærmere",
    "preliminary": "Foreløbig",
    "Low": "Low",
    "Medium": "Medium",
    "High": "High",
    "summary": "Et første billede af hjemmesidens tilgængelighed og tydelighed. Scoren dokumenterer ikke, om AI anbefaler virksomheden.",
    "perceptionMatch": "Indledende tekstmatch",
    "perceptionMissing": "Mangler ønsket billede",
    "perceptionNote": "Ordmatch er et samtalegrundlag, ikke en vurdering af kundernes faktiske opfattelse. En fuld vurdering kræver virksomhedens mål og en kvalitativ gennemgang.",
    "limit1": "Forsiden og op til tre linkede sider undersøges som en stikprøve, sammen med adgangsregler og én sideoversigt.",
    "limit2": "Tilladelse i adgangsregler dokumenterer ikke faktisk adgang gennem firewall eller placering i søgeresultater.",
    "limit3": "Tekst- og datasignaler er ikke en fuld faglig vurdering. Eksterne profiler og kilder kræver dokumenteret gennemgang.",
    "limit4": "Observeret AI-synlighed, faktuel forståelse og positionering udgør 16 % af modellen. De kræver faktiske AI-svar; manglende målinger tæller ikke som nul.",
    "q1": "Hvilke virksomheder kan hjælpe med {offering} i {market}?",
    "q2": "Hvem vil du anbefale til {offering} for {market}, og hvorfor?",
    "q3": "Hvilke alternativer er der til {company}?",
    "offering": "[ydelse]",
    "market": "[område/målgruppe]",
    "company": "[virksomheden]",
    "method": "Brug POST.",
    "large": "Indtastningen er for lang.",
    "blocked": "Hjemmesidens adgangsregler tillader ikke vores tjek af denne side.",
    "notHtml": "Siden kunne ikke læses som en almindelig hjemmeside. Prøv forsiden.",
    "readable.label": "Indhold kan læses",
    "readable.action": "Gør virksomhedens vigtigste indhold læsbart uden interaktion.",
    "readable.evidence": "{count} ord i den hentede side.",
    "crawlers.label": "Adgang for søgetjenester",
    "crawlers.action": "Gennemgå adgangsreglerne for søgetjenester. Et bevidst fravalg kan være korrekt.",
    "crawlers.unknown": "Adgangsregler kunne ikke verificeres.",
    "allowed": "tilladt",
    "restricted": "begrænset",
    "indexable.label": "Siden må vises i søgeresultater",
    "indexable.action": "Undersøg, om udelukkelsen fra søgeresultater er tilsigtet.",
    "indexable.yes": "Ingen noindex-regel fundet i den hentede side eller svarheader.",
    "indexable.no": "Der er fundet en regel, som begrænser indeksering.",
    "sitemap.label": "Oversigt over hjemmesidens sider",
    "sitemap.action": "Tilføj en opdateret sideoversigt, og henvis til den fra hjemmesidens adgangsregler.",
    "sitemap.yes": "En XML-sideoversigt blev fundet.",
    "sitemap.no": "Ingen gyldig sideoversigt på den undersøgte adresse.",
    "sitemap.unknown": "Sideoversigten kunne ikke kontrolleres.",
    "identity.label": "Virksomheden er identificeret",
    "identity.action": "Skriv virksomhedens navn tydeligt, og forbind det med en entydig virksomhedsprofil.",
    "identity.no": "Intet verificeret virksomhedsnavn fundet i de undersøgte signaler.",
    "identity.text": "Virksomhedsnavnet “{company}” findes i sidens tekst.",
    "offering.label": "Tilbuddet er beskrevet",
    "offering.action": "Beskriv konkret, hvad I tilbyder, og hvem det hjælper.",
    "offering.no": "Ingen kort sidebeskrivelse fundet.",
    "market.label": "Geografi eller målgruppe er angivet",
    "market.action": "Angiv tydeligt jeres område og målgruppe på relevante sider.",
    "market.address": "Adresse fundet i virksomhedsdata.",
    "market.audience": "Område eller målgruppe fundet i virksomhedsdata.",
    "market.search": "Søgt efter “{market}” i sidens tekst.",
    "market.no": "Geografi/målgruppe ikke verificeret.",
    "entity.label": "Sammenhængende virksomhedsprofil",
    "entity.action": "Knyt navn, webadresse og kontaktoplysninger sammen i hjemmesidens virksomhedsdata.",
    "entity.yes": "Virksomhedsdata fundet; navn, identitet og kontakt kontrolleret.",
    "entity.no": "Ingen genkendelig virksomhedsprofil i strukturerede data.",
    "sourceNote": "Uddrag fra hjemmesiden vises på originalsproget.",
    "fetchLarge": "Vi kunne ikke hente hjemmesiden teknisk, fordi siden er meget stor. Det betyder ikke nødvendigvis, at AI ikke kan finde virksomheden. Store webshops kan kræve en dybere analyse.",
    "fetchTimeout": "Vi kunne ikke hente hjemmesiden teknisk inden for tidsgrænsen. Det betyder ikke nødvendigvis, at AI ikke kan finde virksomheden. Siden kan være langsom eller kræve en anden hentemetode.",
    "fetchBlocked": "Hjemmesiden ser ud til at afvise vores automatiske serverkald. Det betyder ikke nødvendigvis, at ChatGPT eller søgemaskiner ikke kan finde virksomheden.",
    "fetchPrivate": "Adressen kunne ikke kontrolleres som en offentlig hjemmeside. Private adresser, interne netværk og særlige porte understøttes ikke.",
    "fetchDns": "Domænet kunne ikke slås op lige nu. Kontrollér webadressen, eller prøv igen senere.",
    "fetchFailed": "Vi kunne ikke hente hjemmesiden teknisk. Det betyder ikke nødvendigvis, at AI ikke kan finde virksomheden. Siden kan blokere automatiske kald, være meget tung, eller kræve en anden hentemetode.",
    "master.readable.label": "Adgang til hjemmeside og centrale sider",
    "master.readable.action": "Kontrollér adgang og læsbart indhold på centrale sider.",
    "master.crawlers.label": "Crawlregler og søgeadgang",
    "master.crawlers.action": "Gennemgå søgeadgang særskilt fra adgang til AI-træning.",
    "master.indexable.label": "Indekserbarhed og søgefund",
    "master.indexable.action": "Kontrollér direktiver, canonical og faktiske søgefund.",
    "master.sitemap.label": "Sitemap og interne forbindelser",
    "master.sitemap.action": "Kontrollér at centrale sider findes i sitemap og interne links.",
    "master.identity.label": "Entydig virksomhedsidentitet",
    "master.identity.action": "Sammenhold navn, adresse og kontakt med virksomhedsregistret.",
    "master.offering.label": "Tydelige ydelser og produkter",
    "master.offering.action": "Gennemgå hvad kunden kan købe, og hvilke problemer det løser.",
    "master.market.label": "Målgruppe, geografi og brugssituation",
    "master.market.action": "Dokumentér målgruppe, område og konkrete kundesituationer.",
    "master.expertise.label": "Dokumenteret specialkompetence",
    "master.expertise.action": "Underbyg særlige kompetencer med kontrollerbare belæg.",
    "master.people.label": "Personer bag virksomheden og roller",
    "master.people.action": "Verificér relevante navne og roller i offentlige erhvervskilder.",
    "master.history.label": "Personernes faglige historik",
    "master.history.action": "Undersøg relevant faglig erfaring og forbindelsen til ydelserne.",
    "master.answers.label": "Svar på kundernes konkrete spørgsmål",
    "master.answers.action": "Gennemgå svar om valg, pris, proces og begrænsninger.",
    "master.entity.label": "Indholdsstruktur og konsistens",
    "master.entity.action": "Sammenhold overskrifter, tekst og virksomhedsdata på de undersøgte sider.",
    "master.cases.label": "Cases, referencer og resultater",
    "master.cases.action": "Kontrollér konkrete leverancer og resultater, også hos kunder og partnere.",
    "master.reputation.label": "Ekstern omtale og troværdighed",
    "master.reputation.action": "Undersøg relevante anmeldelser, faglige kilder og uafhængig omtale.",
    "master.consistency.label": "Konsistens på tværs af kilder",
    "master.consistency.action": "Sammenhold oplysninger på hjemmeside, profiler og eksterne kilder.",
    "master.presence.label": "Observeret synlighed ved kundespørgsmål",
    "master.presence.action": "Gennemfør et på forhånd fastlagt testsæt og gem faktiske AI-svar.",
    "master.accuracy.label": "AI-systemets faktuelle forståelse",
    "master.accuracy.action": "Sammenhold et navngivet AI-svar med verificerede fakta.",
    "master.position.label": "Overensstemmelse med ønsket position",
    "master.position.action": "Sammenhold dokumenterede positioneringstemaer med det observerede billede.",
    "master.pending": "Kræver en dokumenteret gennemgang; ikke undersøgt i førstetjekket.",
    "master.signal": "Dette er et signal fra hjemmesiden. Hele kontrolpunktet er endnu ikke vurderet.",
    "master.readable": "{count} undersøgte sider med læsbart indhold. Stikprøven dokumenterer ikke alle centrale sider.",
    "master.sitemap": "{count} adresser i den hentede sideoversigt. Hele sitemap og centrale interne forbindelser kræver gennemgang.",
    "master.sitemapMissing": "Ingen gyldig sideoversigt på den undersøgte adresse; andre adresser og interne links er ikke fuldt undersøgt.",
    "master.identity": "Identiteten er delvist belyst på egen hjemmeside; registeroplysninger er ikke verificeret.",
    "complete": "Færdig",
    "Unknown": "Ikke vurderet",
    "status.fulfilled": "Opfyldt",
    "status.partial": "Delvist opfyldt",
    "status.not_fulfilled": "Ikke opfyldt",
    "status.not_examined": "Ikke undersøgt",
    "status.not_relevant": "Ikke relevant",
    "source.linkedin_company": "LinkedIn · virksomhedsside",
    "source.linkedin_person": "LinkedIn · personprofiler",
    "source.facebook_company": "Facebook · virksomhedsside",
    "source.facebook_public": "Facebook · offentlig erhvervsrelevant omtale",
    "source.google_maps": "Google Maps / virksomhedsprofil",
    "source.reviews": "Trustpilot og brancheportaler",
    "source.registers": "CVR/Virk, Brønnøysundregistrene og Proff",
    "source.professional": "Brancheforeninger og faglige registre",
    "source.media": "Medier og lokale nyheder",
    "source.customers": "Kunders og partneres hjemmesider",
    "source.found_unread": "Link fundet på hjemmesiden; profilens indhold er ikke kontrolleret",
    "source.not_examined": "Ikke undersøgt",
    "source.verified": "Fundet og kontrolleret",
    "source.meaningPending": "Ingen bekræftede eksterne fund endnu.",
    "source.googleTotals": "Google-profilen er matchet via webdomænet. Kun antal og rating er kontrolleret; anmeldelsernes indhold er ikke læst.",
    "source.heading": "Profiler og eksterne kilder",
    "source.intro": "Et link er ikke en verificeret profil. Oversigten viser præcist, hvad der er undersøgt.",
    "source.open": "Se kilde",
    "methodLabel": "Metode {version} · 18 kontrolpunkter",
    "rating": "Vurdering {value}/4 · vægt {weight} %",
    "weightOnly": "Vægt {weight} %",
    "critical": "Væsentlige fund i kontrolpunkt {ids}; se målegrundlaget."
  },
  "nb": {
    "loading": "Vi undersøker nettsiden og tilgangsreglene …",
    "unavailable": "Analysetjenesten er ikke tilgjengelig i denne visningen. Prøv igjen senere.",
    "queue": "Det er kø. Vent tre minutter og prøv igjen.",
    "failed": "Testen kunne ikke gjennomføres. Kontroller nettadressen eller prøv igjen senere. Private adresser støttes ikke.",
    "timeout": "Testen tok for lang tid. Prøv igjen senere.",
    "ready": "Førstesjekken er klar.",
    "coverage": "Datadekning: {coverage} % av den fulle modellen. Risikoen gjelder bare de målte delene.",
    "clarify": "Få avklart: {label}.",
    "presenceAction": "Undersøk faktiske AI-svar på relevante kundespørsmål.",
    "confirmedCount": "{passed} av {total} signaler bekreftet.",
    "someUnknown": "Noen forhold kunne ikke måles.",
    "seeFindings": "Se funnene nedenfor for forklaring og neste skritt.",
    "found": "finnes i sidens tekst",
    "notFound": "ikke funnet i den undersøkte teksten",
    "unknown": "Ikke målt",
    "confirmed": "Bekreftet",
    "review": "Se nærmere",
    "preliminary": "Foreløpig",
    "Low": "Lav",
    "Medium": "Middels",
    "High": "Høy",
    "summary": "Et første bilde av nettsidens tilgjengelighet og tydelighet. Poengsummen dokumenterer ikke om AI anbefaler virksomheten.",
    "perceptionMatch": "Innledende tekstsammenligning",
    "perceptionMissing": "Mangler ønsket bilde",
    "perceptionNote": "Ordtreff er et samtalegrunnlag, ikke en vurdering av kundenes faktiske oppfatning. En full vurdering krever virksomhetens mål og en kvalitativ gjennomgang.",
    "limit1": "Forsiden og opptil tre lenkede sider undersøkes som et utvalg, sammen med tilgangsregler og én sideoversikt.",
    "limit2": "Tillatelse i tilgangsreglene dokumenterer ikke faktisk tilgang gjennom brannmur eller plassering i søkeresultater.",
    "limit3": "Tekst- og datasignaler er ikke en full faglig vurdering. Eksterne profiler og kilder krever dokumentert gjennomgang.",
    "limit4": "Observert AI-synlighet, faktisk forståelse og posisjonering utgjør 16 % av modellen. De krever faktiske AI-svar; manglende målinger teller ikke som null.",
    "q1": "Hvilke virksomheter kan hjelpe med {offering} i {market}?",
    "q2": "Hvem vil du anbefale til {offering} for {market}, og hvorfor?",
    "q3": "Hvilke alternativer finnes til {company}?",
    "offering": "[tjeneste]",
    "market": "[område/målgruppe]",
    "company": "[virksomheten]",
    "method": "Bruk POST.",
    "large": "Inntastingen er for lang.",
    "blocked": "Nettsidens tilgangsregler tillater ikke vår test av denne siden.",
    "notHtml": "Siden kunne ikke leses som en vanlig nettside. Prøv forsiden.",
    "readable.label": "Innholdet kan leses",
    "readable.action": "Gjør virksomhetens viktigste innhold lesbart uten interaksjon.",
    "readable.evidence": "{count} ord på den hentede siden.",
    "crawlers.label": "Tilgang for søketjenester",
    "crawlers.action": "Gå gjennom tilgangsreglene for søketjenester. Et bevisst fravalg kan være riktig.",
    "crawlers.unknown": "Tilgangsreglene kunne ikke verifiseres.",
    "allowed": "tillatt",
    "restricted": "begrenset",
    "indexable.label": "Siden kan vises i søkeresultater",
    "indexable.action": "Undersøk om utelukkelsen fra søkeresultater er tilsiktet.",
    "indexable.yes": "Ingen noindex-regel funnet på den hentede siden eller i svarheaderen.",
    "indexable.no": "Det er funnet en regel som begrenser indeksering.",
    "sitemap.label": "Oversikt over nettstedets sider",
    "sitemap.action": "Legg til en oppdatert sideoversikt og henvis til den fra nettstedets tilgangsregler.",
    "sitemap.yes": "En XML-sideoversikt ble funnet.",
    "sitemap.no": "Ingen gyldig sideoversikt på den undersøkte adressen.",
    "sitemap.unknown": "Sideoversikten kunne ikke kontrolleres.",
    "identity.label": "Virksomheten er identifisert",
    "identity.action": "Skriv virksomhetens navn tydelig og knytt det til en entydig virksomhetsprofil.",
    "identity.no": "Ingen verifisert virksomhetsidentitet funnet i de undersøkte signalene.",
    "identity.text": "Virksomhetsnavnet «{company}» finnes i sidens tekst.",
    "offering.label": "Tilbudet er beskrevet",
    "offering.action": "Beskriv konkret hva dere tilbyr og hvem det hjelper.",
    "offering.no": "Ingen kort sidebeskrivelse funnet.",
    "market.label": "Geografi eller målgruppe er angitt",
    "market.action": "Oppgi tydelig området og målgruppen deres på relevante sider.",
    "market.address": "Adresse funnet i virksomhetsdata.",
    "market.audience": "Område eller målgruppe funnet i virksomhetsdata.",
    "market.search": "Søkt etter «{market}» i sidens tekst.",
    "market.no": "Geografi/målgruppe ikke verifisert.",
    "entity.label": "Sammenhengende virksomhetsprofil",
    "entity.action": "Knytt navn, nettadresse og kontaktinformasjon sammen i nettstedets virksomhetsdata.",
    "entity.yes": "Virksomhetsdata funnet; navn, identitet og kontakt kontrollert.",
    "entity.no": "Ingen gjenkjennelig virksomhetsprofil i strukturerte data.",
    "sourceNote": "Utdrag fra nettsiden vises på originalspråket.",
    "fetchLarge": "Vi kunne ikke hente nettsiden fordi den er svært stor. Dette betyr ikke nødvendigvis at AI ikke kan finne virksomheten. Store nettbutikker kan kreve en grundigere analyse.",
    "fetchTimeout": "Vi kunne ikke hente nettsiden innen tidsfristen. Dette betyr ikke nødvendigvis at AI ikke kan finne virksomheten. Siden kan være treg eller kreve en annen hentemetode.",
    "fetchBlocked": "Nettsiden ser ut til å avvise våre automatiske forespørsler. Dette betyr ikke nødvendigvis at ChatGPT eller søkemotorer ikke kan finne virksomheten.",
    "fetchPrivate": "Adressen kunne ikke bekreftes som en offentlig nettside. Private adresser, interne nettverk og spesielle porter støttes ikke.",
    "fetchDns": "Domenet kunne ikke slås opp akkurat nå. Kontroller nettadressen, eller prøv igjen senere.",
    "fetchFailed": "Vi kunne ikke hente nettsiden teknisk. Dette betyr ikke nødvendigvis at AI ikke kan finne virksomheten. Siden kan blokkere automatiske forespørsler, være svært stor eller kreve en annen hentemetode.",
    "master.readable.label": "Tilgang til nettside og sentrale sider",
    "master.readable.action": "Kontroller tilgang og lesbart innhold på sentrale sider.",
    "master.crawlers.label": "Crawlregler og søketilgang",
    "master.crawlers.action": "Gjennomgå søketilgang separat fra tilgang til AI-trening.",
    "master.indexable.label": "Indekserbarhet og søkefunn",
    "master.indexable.action": "Kontroller direktiver, canonical og faktiske søkefunn.",
    "master.sitemap.label": "Sitemap og interne forbindelser",
    "master.sitemap.action": "Kontroller at sentrale sider finnes i sitemap og interne lenker.",
    "master.identity.label": "Entydig virksomhetsidentitet",
    "master.identity.action": "Sammenhold navn, adresse og kontakt med foretaksregisteret.",
    "master.offering.label": "Tydelige tjenester og produkter",
    "master.offering.action": "Gå gjennom hva kunden kan kjøpe, og hvilke problemer det løser.",
    "master.market.label": "Målgruppe, geografi og brukssituasjon",
    "master.market.action": "Dokumenter målgruppe, område og konkrete kundesituasjoner.",
    "master.expertise.label": "Dokumentert spesialkompetanse",
    "master.expertise.action": "Underbygg spesialkompetanse med kontrollerbar dokumentasjon.",
    "master.people.label": "Personene bak virksomheten og roller",
    "master.people.action": "Verifiser relevante navn og roller i offentlige næringskilder.",
    "master.history.label": "Personenes faglige historikk",
    "master.history.action": "Undersøk relevant faglig erfaring og forbindelsen til tjenestene.",
    "master.answers.label": "Svar på kundenes konkrete spørsmål",
    "master.answers.action": "Gjennomgå svar om valg, pris, prosess og begrensninger.",
    "master.entity.label": "Innholdsstruktur og konsistens",
    "master.entity.action": "Sammenhold overskrifter, tekst og virksomhetsdata på undersøkte sider.",
    "master.cases.label": "Kundecaser, referanser og resultater",
    "master.cases.action": "Kontroller konkrete leveranser og resultater, også hos kunder og partnere.",
    "master.reputation.label": "Ekstern omtale og troverdighet",
    "master.reputation.action": "Undersøk relevante anmeldelser, faglige kilder og uavhengig omtale.",
    "master.consistency.label": "Konsistens på tvers av kilder",
    "master.consistency.action": "Sammenhold opplysninger på nettside, profiler og eksterne kilder.",
    "master.presence.label": "Observert synlighet ved kundespørsmål",
    "master.presence.action": "Gjennomfør et forhåndsdefinert testsett og lagre faktiske AI-svar.",
    "master.accuracy.label": "AI-systemets faktiske forståelse",
    "master.accuracy.action": "Sammenhold et navngitt AI-svar med verifiserte fakta.",
    "master.position.label": "Samsvar med ønsket posisjon",
    "master.position.action": "Sammenhold dokumenterte posisjoneringstemaer med det observerte bildet.",
    "master.pending": "Krever dokumentert gjennomgang; ikke undersøkt i førstesjekken.",
    "master.signal": "Dette er et signal fra nettsiden. Hele kontrollpunktet er ennå ikke vurdert.",
    "master.readable": "{count} undersøkte sider med lesbart innhold. Utvalget dokumenterer ikke alle sentrale sider.",
    "master.sitemap": "{count} adresser i hentet sideoversikt. Hele sitemap og sentrale interne forbindelser krever gjennomgang.",
    "master.sitemapMissing": "Ingen gyldig sideoversikt på undersøkt adresse; andre adresser og interne lenker er ikke fullt undersøkt.",
    "master.identity": "Identiteten er delvis belyst på egen nettside; registeropplysninger er ikke verifisert.",
    "complete": "Ferdig",
    "Unknown": "Ikke vurdert",
    "status.fulfilled": "Oppfylt",
    "status.partial": "Delvis oppfylt",
    "status.not_fulfilled": "Ikke oppfylt",
    "status.not_examined": "Ikke undersøkt",
    "status.not_relevant": "Ikke relevant",
    "source.linkedin_company": "LinkedIn · virksomhetsside",
    "source.linkedin_person": "LinkedIn · personprofiler",
    "source.facebook_company": "Facebook · virksomhetsside",
    "source.facebook_public": "Facebook · offentlig næringsrelevant omtale",
    "source.google_maps": "Google Maps / virksomhetsprofil",
    "source.reviews": "Trustpilot og bransjeportaler",
    "source.registers": "CVR/Virk, Brønnøysundregistrene og Proff",
    "source.professional": "Bransjeforeninger og faglige registre",
    "source.media": "Medier og lokale nyheter",
    "source.customers": "Kunders og partneres nettsider",
    "source.found_unread": "Lenke funnet på nettsiden; profilinnholdet er ikke kontrollert",
    "source.not_examined": "Ikke undersøkt",
    "source.verified": "Funnet og kontrollert",
    "source.meaningPending": "Ingen bekreftede eksterne funn ennå.",
    "source.googleTotals": "Google-profilen er matchet via nettdomenet. Bare antall og rating er kontrollert; anmeldelsenes innhold er ikke lest.",
    "source.heading": "Profiler og eksterne kilder",
    "source.intro": "En lenke er ikke en verifisert profil. Oversikten viser nøyaktig hva som er undersøkt.",
    "source.open": "Se kilde",
    "methodLabel": "Metode {version} · 18 kontrollpunkter",
    "rating": "Vurdering {value}/4 · vekt {weight} %",
    "weightOnly": "Vekt {weight} %",
    "critical": "Vesentlige funn i kontrollpunkt {ids}; se målegrunnlaget."
  },
  "en": {
    "loading": "We are checking the website and its access rules …",
    "unavailable": "The analysis service is unavailable in this view. Please try again later.",
    "queue": "The check is busy. Wait three minutes and try again.",
    "failed": "The check could not be completed. Check the website address or try again later. Private addresses are not supported.",
    "timeout": "The check timed out. Please try again later.",
    "ready": "Your initial check is ready.",
    "coverage": "Data coverage: {coverage}% of the full model. Risk applies only to the measured parts.",
    "clarify": "Clarify: {label}.",
    "presenceAction": "Examine actual AI responses to relevant customer questions.",
    "confirmedCount": "{passed} of {total} signals confirmed.",
    "someUnknown": "Some items could not be measured.",
    "seeFindings": "See the findings below for explanations and next steps.",
    "found": "found in the page text",
    "notFound": "not found in the text examined",
    "unknown": "Not measured",
    "confirmed": "Confirmed",
    "review": "Review",
    "preliminary": "Preliminary",
    "Low": "Low",
    "Medium": "Medium",
    "High": "High",
    "summary": "An initial view of the website’s accessibility and clarity. The score does not establish whether AI recommends the business.",
    "perceptionMatch": "Initial text comparison",
    "perceptionMissing": "Desired perception not provided",
    "perceptionNote": "Word matches are a starting point for discussion, not a measure of actual customer perception. A full assessment requires business goals and a qualitative review.",
    "limit1": "The submitted page and up to three linked pages are sampled, along with crawler rules and one sitemap.",
    "limit2": "Permission in access rules does not establish actual access through a firewall or placement in search results.",
    "limit3": "Text and data signals are not a full professional assessment. External profiles and sources require a documented review.",
    "limit4": "Observed AI visibility, factual understanding and positioning make up 16% of the model. They require actual AI responses; missing measurements do not count as zero.",
    "q1": "Which businesses can help with {offering} in {market}?",
    "q2": "Who would you recommend for {offering} for {market}, and why?",
    "q3": "What alternatives are there to {company}?",
    "offering": "[service]",
    "market": "[area/audience]",
    "company": "[business]",
    "method": "Use POST.",
    "large": "The input is too long.",
    "blocked": "The website’s access rules do not allow us to check this page.",
    "notHtml": "The page could not be read as a standard web page. Try the homepage.",
    "readable.label": "Content can be read",
    "readable.action": "Make the business’s key content readable without interaction.",
    "readable.evidence": "{count} words in the retrieved page.",
    "crawlers.label": "Access for search services",
    "crawlers.action": "Review access rules for search services. An intentional restriction may be appropriate.",
    "crawlers.unknown": "Access rules could not be verified.",
    "allowed": "allowed",
    "restricted": "restricted",
    "indexable.label": "Page permitted in search results",
    "indexable.action": "Check whether exclusion from search results is intentional.",
    "indexable.yes": "No noindex rule found in the retrieved page or response header.",
    "indexable.no": "A rule restricting indexing was found.",
    "sitemap.label": "Index of website pages",
    "sitemap.action": "Add an up-to-date sitemap and reference it in the website’s access rules.",
    "sitemap.yes": "An XML sitemap was found.",
    "sitemap.no": "No valid sitemap at the address checked.",
    "sitemap.unknown": "The sitemap could not be checked.",
    "identity.label": "Business identity found",
    "identity.action": "State the business name clearly and link it to an unambiguous business profile.",
    "identity.no": "No verified business name found in the signals examined.",
    "identity.text": "The business name “{company}” appears in the page text.",
    "offering.label": "Offering described",
    "offering.action": "Describe specifically what you offer and who it helps.",
    "offering.no": "No short page description found.",
    "market.label": "Location or audience specified",
    "market.action": "Clearly state your area and audience on relevant pages.",
    "market.address": "Address found in business data.",
    "market.audience": "Area or audience found in business data.",
    "market.search": "Searched for “{market}” in the page text.",
    "market.no": "Location/audience not verified.",
    "entity.label": "Connected business profile",
    "entity.action": "Connect the name, website address and contact details in the website’s business data.",
    "entity.yes": "Business data found; name, identity and contact checked.",
    "entity.no": "No recognisable business profile in structured data.",
    "sourceNote": "Website excerpts are shown in their original language.",
    "fetchLarge": "We could not retrieve the website because it is very large. This does not necessarily mean AI cannot find the business. Large online stores may require a deeper analysis.",
    "fetchTimeout": "We could not retrieve the website within the time limit. This does not necessarily mean AI cannot find the business. The site may be slow or require a different retrieval method.",
    "fetchBlocked": "The website appears to reject our automated requests. This does not necessarily mean ChatGPT or search engines cannot find the business.",
    "fetchPrivate": "The address could not be verified as a public website. Private addresses, internal networks and non-standard ports are not supported.",
    "fetchDns": "The domain could not be resolved right now. Check the web address or try again later.",
    "fetchFailed": "We could not technically retrieve the website. This does not necessarily mean AI cannot find the business. The site may block automated requests, be very large or require a different retrieval method.",
    "master.readable.label": "Access to the website and essential pages",
    "master.readable.action": "Check access and readable content on essential pages.",
    "master.crawlers.label": "Crawler rules and search access",
    "master.crawlers.action": "Review search access separately from AI training access.",
    "master.indexable.label": "Indexability and search findings",
    "master.indexable.action": "Check directives, canonical URLs and actual search results.",
    "master.sitemap.label": "Sitemap and internal links",
    "master.sitemap.action": "Check that essential pages appear in the sitemap and internal links.",
    "master.identity.label": "Unambiguous business identity",
    "master.identity.action": "Compare name, address and contact details with official business records.",
    "master.offering.label": "Clear services and products",
    "master.offering.action": "Review what customers can buy and which problems it solves.",
    "master.market.label": "Audience, geography and use cases",
    "master.market.action": "Document audience, location and concrete customer situations.",
    "master.expertise.label": "Documented specialist expertise",
    "master.expertise.action": "Support specialist claims with verifiable evidence.",
    "master.people.label": "People behind the business and their roles",
    "master.people.action": "Verify relevant names and roles in public business sources.",
    "master.history.label": "Professional track record of the people",
    "master.history.action": "Review relevant experience and its connection to the services.",
    "master.answers.label": "Answers to concrete customer questions",
    "master.answers.action": "Review answers about selection, price, process and limitations.",
    "master.entity.label": "Content structure and consistency",
    "master.entity.action": "Compare headings, text and business data across examined pages.",
    "master.cases.label": "Case studies, references and results",
    "master.cases.action": "Verify concrete work and results, including customer and partner sources.",
    "master.reputation.label": "External coverage and credibility",
    "master.reputation.action": "Review relevant reviews, professional sources and independent coverage.",
    "master.consistency.label": "Consistency across sources",
    "master.consistency.action": "Compare details on the website, profiles and external sources.",
    "master.presence.label": "Observed visibility for customer questions",
    "master.presence.action": "Run a predefined test panel and save actual AI responses.",
    "master.accuracy.label": "Factual accuracy of AI understanding",
    "master.accuracy.action": "Compare an AI answer naming the business with verified facts.",
    "master.position.label": "Alignment with documented desired positioning",
    "master.position.action": "Compare documented positioning themes with the observed picture.",
    "master.pending": "Requires a documented review; not examined in this initial check.",
    "master.signal": "This is a website signal. The full checkpoint has not been assessed.",
    "master.readable": "{count} sampled pages with readable content. The sample does not establish access to every essential page.",
    "master.sitemap": "{count} URLs in the fetched sitemap. The full sitemap and essential internal links require review.",
    "master.sitemapMissing": "No valid sitemap at the examined location; alternative locations and internal links have not been fully checked.",
    "master.identity": "Identity is partly evidenced on the own website; official records have not been verified.",
    "complete": "Complete",
    "Unknown": "Not assessed",
    "status.fulfilled": "Fulfilled",
    "status.partial": "Partly fulfilled",
    "status.not_fulfilled": "Not fulfilled",
    "status.not_examined": "Not examined",
    "status.not_relevant": "Not relevant",
    "source.linkedin_company": "LinkedIn · company page",
    "source.linkedin_person": "LinkedIn · personal profiles",
    "source.facebook_company": "Facebook · company page",
    "source.facebook_public": "Facebook · public business-related coverage",
    "source.google_maps": "Google Maps / Business Profile",
    "source.reviews": "Trustpilot and industry portals",
    "source.registers": "Official business registers and Proff",
    "source.professional": "Industry associations and professional registers",
    "source.media": "Media and local news",
    "source.customers": "Customer and partner websites",
    "source.found_unread": "Link found on the website; profile content not checked",
    "source.not_examined": "Not examined",
    "source.verified": "Found and checked",
    "source.meaningPending": "No verified external findings yet.",
    "source.googleTotals": "Google profile matched by website domain. Only review count and rating checked; individual reviews not read.",
    "source.heading": "Profiles and external sources",
    "source.intro": "A link is not a verified profile. This inventory shows exactly what was examined.",
    "source.open": "View source",
    "methodLabel": "Method {version} · 18 checkpoints",
    "rating": "Assessment {value}/4 · weight {weight}%",
    "weightOnly": "Weight {weight}%",
    "critical": "Material findings in checkpoint {ids}; see the evidence."
  },
  "de": {
    "loading": "Wir prüfen die Website und ihre Zugangsregeln …",
    "unavailable": "Der Analysedienst ist in dieser Ansicht nicht verfügbar. Bitte versuchen Sie es später erneut.",
    "queue": "Der Check ist ausgelastet. Warten Sie drei Minuten und versuchen Sie es erneut.",
    "failed": "Der Check konnte nicht abgeschlossen werden. Prüfen Sie die Webadresse oder versuchen Sie es später erneut. Private Adressen werden nicht unterstützt.",
    "timeout": "Der Check hat zu lange gedauert. Bitte versuchen Sie es später erneut.",
    "ready": "Ihr Erstcheck ist fertig.",
    "coverage": "Datenabdeckung: {coverage} % des vollständigen Modells. Das Risiko bezieht sich nur auf die gemessenen Teile.",
    "clarify": "Klären Sie: {label}.",
    "presenceAction": "Untersuchen Sie tatsächliche KI-Antworten auf relevante Kundenfragen.",
    "confirmedCount": "{passed} von {total} Signalen bestätigt.",
    "someUnknown": "Einige Aspekte konnten nicht gemessen werden.",
    "seeFindings": "Erläuterungen und nächste Schritte finden Sie in den Ergebnissen unten.",
    "found": "im Seitentext gefunden",
    "notFound": "im untersuchten Text nicht gefunden",
    "unknown": "Nicht gemessen",
    "confirmed": "Bestätigt",
    "review": "Näher prüfen",
    "preliminary": "Vorläufig",
    "Low": "Niedrig",
    "Medium": "Mittel",
    "High": "Hoch",
    "summary": "Ein erster Eindruck von Zugänglichkeit und Klarheit der Website. Die Bewertung belegt nicht, ob KI das Unternehmen empfiehlt.",
    "perceptionMatch": "Erster Textabgleich",
    "perceptionMissing": "Gewünschtes Bild nicht angegeben",
    "perceptionNote": "Worttreffer sind eine Gesprächsgrundlage, keine Bewertung der tatsächlichen Kundenwahrnehmung. Eine vollständige Bewertung erfordert Unternehmensziele und eine qualitative Prüfung.",
    "limit1": "Die eingegebene Seite und bis zu drei verlinkte Seiten werden zusammen mit Zugangsregeln und einer Sitemap stichprobenartig untersucht.",
    "limit2": "Eine Erlaubnis in den Zugangsregeln belegt weder tatsächlichen Zugriff durch eine Firewall noch eine Platzierung in Suchergebnissen.",
    "limit3": "Text- und Datensignale sind keine vollständige fachliche Bewertung. Externe Profile und Quellen erfordern dokumentierte Prüfung.",
    "limit4": "Beobachtete KI-Sichtbarkeit, faktisches Verständnis und Positionierung machen 16 % des Modells aus. Sie erfordern tatsächliche KI-Antworten; fehlende Messungen zählen nicht als null.",
    "q1": "Welche Unternehmen können bei {offering} in {market} helfen?",
    "q2": "Wen würden Sie für {offering} für {market} empfehlen und warum?",
    "q3": "Welche Alternativen gibt es zu {company}?",
    "offering": "[Leistung]",
    "market": "[Region/Zielgruppe]",
    "company": "[Unternehmen]",
    "method": "Verwenden Sie POST.",
    "large": "Die Eingabe ist zu lang.",
    "blocked": "Die Zugangsregeln der Website erlauben unseren Check dieser Seite nicht.",
    "notHtml": "Die Seite konnte nicht als normale Webseite gelesen werden. Versuchen Sie die Startseite.",
    "readable.label": "Inhalte sind lesbar",
    "readable.action": "Machen Sie die wichtigsten Unternehmensinhalte ohne Interaktion lesbar.",
    "readable.evidence": "{count} Wörter auf der abgerufenen Seite.",
    "crawlers.label": "Zugang für Suchdienste",
    "crawlers.action": "Prüfen Sie die Zugangsregeln für Suchdienste. Eine bewusste Einschränkung kann richtig sein.",
    "crawlers.unknown": "Die Zugangsregeln konnten nicht überprüft werden.",
    "allowed": "erlaubt",
    "restricted": "eingeschränkt",
    "indexable.label": "Anzeige in Suchergebnissen zulässig",
    "indexable.action": "Prüfen Sie, ob der Ausschluss aus Suchergebnissen beabsichtigt ist.",
    "indexable.yes": "Keine noindex-Regel auf der abgerufenen Seite oder im Antwortheader gefunden.",
    "indexable.no": "Eine Regel zur Einschränkung der Indexierung wurde gefunden.",
    "sitemap.label": "Übersicht der Website-Seiten",
    "sitemap.action": "Erstellen Sie eine aktuelle Sitemap und verweisen Sie in den Zugangsregeln darauf.",
    "sitemap.yes": "Eine XML-Sitemap wurde gefunden.",
    "sitemap.no": "Keine gültige Sitemap unter der untersuchten Adresse.",
    "sitemap.unknown": "Die Sitemap konnte nicht geprüft werden.",
    "identity.label": "Unternehmen identifiziert",
    "identity.action": "Geben Sie den Unternehmensnamen klar an und verbinden Sie ihn mit einem eindeutigen Unternehmensprofil.",
    "identity.no": "Kein bestätigter Unternehmensname in den untersuchten Signalen gefunden.",
    "identity.text": "Der Unternehmensname „{company}“ erscheint im Seitentext.",
    "offering.label": "Angebot beschrieben",
    "offering.action": "Beschreiben Sie konkret, was Sie anbieten und wem es hilft.",
    "offering.no": "Keine kurze Seitenbeschreibung gefunden.",
    "market.label": "Region oder Zielgruppe angegeben",
    "market.action": "Geben Sie Ihre Region und Zielgruppe auf relevanten Seiten klar an.",
    "market.address": "Adresse in den Unternehmensdaten gefunden.",
    "market.audience": "Region oder Zielgruppe in den Unternehmensdaten gefunden.",
    "market.search": "Im Seitentext nach „{market}“ gesucht.",
    "market.no": "Region/Zielgruppe nicht bestätigt.",
    "entity.label": "Zusammenhängendes Unternehmensprofil",
    "entity.action": "Verknüpfen Sie Name, Webadresse und Kontaktdaten in den Unternehmensdaten Ihrer Website.",
    "entity.yes": "Unternehmensdaten gefunden; Name, Identität und Kontakt geprüft.",
    "entity.no": "Kein erkennbares Unternehmensprofil in strukturierten Daten.",
    "sourceNote": "Website-Auszüge werden in der Originalsprache angezeigt.",
    "fetchLarge": "Die Website konnte wegen ihrer Größe nicht abgerufen werden. Das bedeutet nicht zwangsläufig, dass KI das Unternehmen nicht finden kann. Große Onlineshops können eine vertiefte Analyse erfordern.",
    "fetchTimeout": "Die Website konnte nicht innerhalb des Zeitlimits abgerufen werden. Das bedeutet nicht zwangsläufig, dass KI das Unternehmen nicht finden kann. Die Seite ist möglicherweise langsam oder erfordert eine andere Abrufmethode.",
    "fetchBlocked": "Die Website scheint unsere automatisierten Anfragen abzulehnen. Das bedeutet nicht zwangsläufig, dass ChatGPT oder Suchmaschinen das Unternehmen nicht finden können.",
    "fetchPrivate": "Die Adresse konnte nicht als öffentliche Website bestätigt werden. Private Adressen, interne Netzwerke und besondere Ports werden nicht unterstützt.",
    "fetchDns": "Die Domain konnte gerade nicht aufgelöst werden. Prüfen Sie die Webadresse oder versuchen Sie es später erneut.",
    "fetchFailed": "Die Website konnte technisch nicht abgerufen werden. Das bedeutet nicht zwangsläufig, dass KI das Unternehmen nicht finden kann. Die Seite blockiert möglicherweise automatisierte Anfragen, ist sehr groß oder erfordert eine andere Abrufmethode.",
    "master.readable.label": "Zugang zur Website und wesentlichen Seiten",
    "master.readable.action": "Zugang und lesbare Inhalte der wesentlichen Seiten prüfen.",
    "master.crawlers.label": "Crawler-Regeln und Suchzugang",
    "master.crawlers.action": "Suchzugang getrennt vom Zugang für KI-Training prüfen.",
    "master.indexable.label": "Indexierbarkeit und Suchergebnisse",
    "master.indexable.action": "Direktiven, kanonische URLs und tatsächliche Suchergebnisse prüfen.",
    "master.sitemap.label": "Sitemap und interne Links",
    "master.sitemap.action": "Wesentliche Seiten in Sitemap und internen Links prüfen.",
    "master.identity.label": "Eindeutige Unternehmensidentität",
    "master.identity.action": "Name, Anschrift und Kontaktdaten mit dem Unternehmensregister abgleichen.",
    "master.offering.label": "Klare Dienstleistungen und Produkte",
    "master.offering.action": "Prüfen, was Kunden kaufen können und welche Probleme es löst.",
    "master.market.label": "Zielgruppe, Region und Einsatzfälle",
    "master.market.action": "Zielgruppe, Region und konkrete Kundensituationen dokumentieren.",
    "master.expertise.label": "Belegte Fachkompetenz",
    "master.expertise.action": "Fachkompetenz mit überprüfbaren Belegen untermauern.",
    "master.people.label": "Personen hinter dem Unternehmen und ihre Rollen",
    "master.people.action": "Relevante Namen und Rollen in öffentlichen Wirtschaftsquellen bestätigen.",
    "master.history.label": "Beruflicher Werdegang der Personen",
    "master.history.action": "Relevante Erfahrung und ihren Bezug zu den Leistungen prüfen.",
    "master.answers.label": "Antworten auf konkrete Kundenfragen",
    "master.answers.action": "Antworten zu Auswahl, Preis, Ablauf und Grenzen prüfen.",
    "master.entity.label": "Inhaltsstruktur und Konsistenz",
    "master.entity.action": "Überschriften, Text und Unternehmensdaten der untersuchten Seiten abgleichen.",
    "master.cases.label": "Fallstudien, Referenzen und Ergebnisse",
    "master.cases.action": "Konkrete Leistungen und Ergebnisse auch bei Kunden und Partnern prüfen.",
    "master.reputation.label": "Externe Erwähnungen und Glaubwürdigkeit",
    "master.reputation.action": "Relevante Bewertungen, Fachquellen und unabhängige Erwähnungen prüfen.",
    "master.consistency.label": "Konsistenz zwischen Quellen",
    "master.consistency.action": "Angaben auf Website, Profilen und externen Quellen abgleichen.",
    "master.presence.label": "Beobachtete Sichtbarkeit bei Kundenfragen",
    "master.presence.action": "Einen vorher festgelegten Test durchführen und tatsächliche KI-Antworten speichern.",
    "master.accuracy.label": "Faktische Richtigkeit des KI-Verständnisses",
    "master.accuracy.action": "Eine KI-Antwort zum benannten Unternehmen mit bestätigten Fakten abgleichen.",
    "master.position.label": "Übereinstimmung mit der dokumentierten Wunschposition",
    "master.position.action": "Dokumentierte Positionierungsthemen mit dem beobachteten Bild abgleichen.",
    "master.pending": "Erfordert eine dokumentierte Prüfung; im Erstcheck nicht untersucht.",
    "master.signal": "Dies ist ein Website-Signal. Der vollständige Kontrollpunkt wurde noch nicht bewertet.",
    "master.readable": "{count} untersuchte Seiten mit lesbarem Inhalt. Die Stichprobe belegt nicht den Zugang zu allen wesentlichen Seiten.",
    "master.sitemap": "{count} URLs in der abgerufenen Sitemap. Die vollständige Sitemap und wesentliche interne Links erfordern Prüfung.",
    "master.sitemapMissing": "Keine gültige Sitemap an der geprüften Adresse; andere Adressen und interne Links wurden nicht vollständig geprüft.",
    "master.identity": "Identität teilweise auf eigener Website belegt; Registerangaben nicht bestätigt.",
    "complete": "Vollständig",
    "Unknown": "Nicht bewertet",
    "status.fulfilled": "Erfüllt",
    "status.partial": "Teilweise erfüllt",
    "status.not_fulfilled": "Nicht erfüllt",
    "status.not_examined": "Nicht untersucht",
    "status.not_relevant": "Nicht relevant",
    "source.linkedin_company": "LinkedIn · Unternehmensseite",
    "source.linkedin_person": "LinkedIn · Personenprofile",
    "source.facebook_company": "Facebook · Unternehmensseite",
    "source.facebook_public": "Facebook · öffentliche geschäftliche Erwähnungen",
    "source.google_maps": "Google Maps / Unternehmensprofil",
    "source.reviews": "Trustpilot und Branchenportale",
    "source.registers": "Unternehmensregister und Proff",
    "source.professional": "Branchenverbände und Fachregister",
    "source.media": "Medien und lokale Nachrichten",
    "source.customers": "Kunden- und Partner-Websites",
    "source.found_unread": "Link auf der Website gefunden; Profilinhalt nicht geprüft",
    "source.not_examined": "Nicht untersucht",
    "source.verified": "Gefunden und geprüft",
    "source.meaningPending": "Noch keine bestätigten externen Befunde.",
    "source.googleTotals": "Google-Profil über Website-Domain zugeordnet. Nur Anzahl und Bewertung geprüft; einzelne Rezensionen nicht gelesen.",
    "source.heading": "Profile und externe Quellen",
    "source.intro": "Ein Link ist kein bestätigtes Profil. Diese Übersicht zeigt genau, was untersucht wurde.",
    "source.open": "Quelle ansehen",
    "methodLabel": "Methode {version} · 18 Kontrollpunkte",
    "rating": "Bewertung {value}/4 · Gewicht {weight} %",
    "weightOnly": "Gewicht {weight} %",
    "critical": "Wesentliche Befunde in Kontrollpunkt {ids}; siehe Prüfgrundlage."
  }
};
export function language(value) { return ({dk:'da',no:'nb',da:'da',nb:'nb',en:'en',de:'de'})[value] || 'da'; }
export function translator(locale) {
 const messages=copy[language(locale)];
 return (key,values={}) => (messages[key] || copy.da[key] || key).replace(/\{(\w+)\}/g,(_,name)=>String(values[name] ?? ''));
}
