document.querySelectorAll('[data-website-check]').forEach(component=>{
  const form=component.querySelector('form'),input=component.querySelector('input'),analysis=component.querySelector('[data-analysis]'),title=component.querySelector('[data-analysis-title]'),bar=component.querySelector('[data-progress]'),steps=[...component.querySelectorAll('[data-check-step]')],results=component.querySelector('[data-results]'),mail=component.querySelector('[data-mail-cta]'),page=component.dataset.sourcePage||window.location.href;
  const language=(document.documentElement.lang||'da').split('-')[0];
  const copy={da:{invalid:'Skriv en gyldig webadresse, for eksempel virksomhed.dk',title:'Første overblik over ',hello:'Hej Waltham',request:'Jeg vil gerne have en indledende vurdering af ',goal:'Det vigtigste, hjemmesiden skal skabe, er:',describe:'[Beskriv kort kunde, henvendelse, booking eller salg]',contact:'I må gerne kontakte mig for en indledende og uforpligtende afklaring.',source:'Jeg henvender mig fra denne side:',regards:'Venlig hilsen'},nb:{invalid:'Skriv inn en gyldig nettadresse, for eksempel virksomhet.no',title:'Første overblikk over ',hello:'Hei Waltham',request:'Jeg vil gjerne ha en innledende vurdering av ',goal:'Det viktigste nettstedet skal skape, er:',describe:'[Beskriv kort kunde, henvendelse, booking eller salg]',contact:'Ta gjerne kontakt for en innledende og uforpliktende avklaring.',source:'Jeg henvender meg fra denne siden:',regards:'Vennlig hilsen'},en:{invalid:'Enter a valid web address, for example company.com',title:'Initial overview of ',hello:'Hello Waltham',request:'I would like an initial assessment of ',goal:'The most important outcome the website should create is:',describe:'[Briefly describe the customer, enquiry, booking or sale]',contact:'Please contact me for an initial, no-obligation conversation.',source:'My enquiry comes from this page:',regards:'Kind regards'},de:{invalid:'Geben Sie eine gültige Webadresse ein, zum Beispiel unternehmen.de',title:'Erster Überblick zu ',hello:'Hallo Waltham',request:'Ich wünsche eine erste Einschätzung von ',goal:'Das wichtigste Ziel der Website ist:',describe:'[Kunde, Anfrage, Buchung oder Verkauf kurz beschreiben]',contact:'Bitte kontaktieren Sie mich für ein unverbindliches Erstgespräch.',source:'Meine Anfrage kommt von dieser Seite:',regards:'Freundliche Grüße'}}[language]||null;
  const words=copy||{invalid:'Skriv en gyldig webadresse, for eksempel virksomhed.dk',title:'Første overblik over ',hello:'Hej Waltham',request:'Jeg vil gerne have en indledende vurdering af ',goal:'Det vigtigste, hjemmesiden skal skabe, er:',describe:'[Beskriv kort kunde, henvendelse, booking eller salg]',contact:'I må gerne kontakte mig for en indledende og uforpligtende afklaring.',source:'Jeg henvender mig fra denne side:',regards:'Venlig hilsen'};
  const clean=value=>value.trim().toLowerCase().replace(/^https?:\/\//,'').replace(/^www\./,'').split('/')[0];
  form.addEventListener('submit',event=>{
    event.preventDefault();const domain=clean(input.value);
    if(!/^[a-z0-9.-]+\.[a-z]{2,}$/i.test(domain)){input.setCustomValidity(words.invalid);input.reportValidity();input.focus();return}
    input.setCustomValidity('');input.value=domain;analysis.classList.add('active');results.classList.remove('visible');steps.forEach(step=>step.classList.remove('done'));bar.style.width='0';title.textContent=words.title+domain;
    const subject='Waltham | Digital Opportunity Scan: '+domain;
    const body=words.hello+',\n\n'+words.request+domain+'.\n\n'+words.goal+'\n'+words.describe+'\n\n'+words.contact+'\n\n'+words.source+'\n'+page+'\n\n'+words.regards+'\n[Navn / Name]';
    mail.href='mailto:waltham@me.com?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);
    steps.forEach((step,index)=>setTimeout(()=>{step.classList.add('done');bar.style.width=((index+1)/steps.length*100)+'%';if(index===steps.length-1)results.classList.add('visible')},350+index*450));analysis.scrollIntoView({behavior:'smooth',block:'nearest'});
  });
  input.addEventListener('input',()=>input.setCustomValidity(''));
});
