import test from 'node:test';import assert from 'node:assert/strict';
import {publicAddress,normalize,allowed,analyze} from '../netlify/functions/lib/visibility.mjs';
import handler from '../netlify/functions/ai-visibility.mjs';
test('reject private, reserved and mapped addresses',()=>{
 for(const ip of ['127.0.0.1','10.1.1.1','169.254.169.254','172.16.0.1','192.168.1.1','100.64.0.1','::1','::ffff:127.0.0.1','::ffff:7f00:1','fe80::1','fc00::1','2001:db8::1','198.18.0.1'])assert.equal(publicAddress(ip),false,ip);
 for(const ip of ['8.8.8.8','1.1.1.1','2606:4700:4700::1111'])assert.equal(publicAddress(ip),true,ip);
});
test('URL normalization rejects credentials, schemes and ports',()=>{assert.equal(normalize('example.com').href,'https://example.com/');for(const x of ['file:///etc/passwd','http://user:pw@example.com','http://example.com:9999'])assert.throws(()=>normalize(x));});
test('robots specific groups, merged groups, wildcards and allow ties',()=>{
 const rules='User-agent: *\nDisallow: /\nUser-agent: OAI-SearchBot\nDisallow: /private*\nAllow: /private/public$\nUser-agent: OAI-SearchBot\nDisallow: /secret';
 assert.equal(allowed(rules,'OAI-SearchBot','/'),true);assert.equal(allowed(rules,'OAI-SearchBot','/private/x'),false);assert.equal(allowed(rules,'OAI-SearchBot','/private/public'),true);assert.equal(allowed(rules,'OAI-SearchBot','/secret'),false);assert.equal(allowed(rules,'GPTBot','/'),false);
 assert.equal(allowed('User-agent: *\nDisallow: /x\nAllow: /x','x','/x'),true);
});
const page={url:'https://example.com/',headers:{'content-type':'text/html'},text:'<title>Eksempel</title><h1>Rådgivning</h1><meta content="En lokal virksomhed med personlig rådgivning til familier og virksomheder på Fyn." name="description"><script type="application/ld+json">{"@type":"BankOrCreditUnion","name":"Eksempel","url":"https://example.com","address":"Fyn"}</script>'+('personlig rådgivning '.repeat(70))};
test('complete technical foundation remains provisional, presence unknown',()=>{const r=analyze({page,robots:{status:404,text:''},sitemap:{status:200,text:'<urlset></urlset>'},profile:{desired:'personlig, digital'}});assert.equal(r.score,10);assert.equal(r.coverage,70);assert.equal(r.presence.status,'Ikke målt');assert.deepEqual(r.presence.competitors,[]);assert.equal(r.perception.comparisons[0].found,true);assert.equal(r.perception.comparisons[1].found,false);});
test('unknown robots excluded, not rewarded; noindex header counted',()=>{const r=analyze({page:{...page,headers:{'x-robots-tag':'noindex'}},robots:null,sitemap:null});assert.equal(r.coverage,45);assert.equal(r.checks.find(c=>c.label.includes('søgeresultater')).pass,false);});
test('training restrictions do not reduce score',()=>{const r=analyze({page,robots:{status:200,text:'User-agent: GPTBot\nDisallow: /'},sitemap:{status:200,text:'<urlset/>'}});assert.equal(r.score,10);});
test('HTML masquerading as robots is unknown; invalid schema is not business identity',()=>{const r=analyze({page:{...page,text:'<h1>x</h1><script type="application/ld+json">invalid</script>'},robots:{status:200,text:'<html>error</html>'},sitemap:{status:200,text:'<html>error</html>'}});assert.equal(r.coverage,50);assert.equal(r.checks.find(c=>c.label==='Virksomheden er identificeret').pass,false);});
test('handler rejects wrong methods and malformed payload',async()=>{assert.equal((await handler(new Request('http://localhost'))).status,405);assert.equal((await handler(new Request('http://localhost',{method:'POST',body:'{'}))).status,400);});
test('Danish HTML entities and metadata geography are decoded',()=>{const r=analyze({page:{...page,text:'<h1>Fr&#xF8;rup</h1><meta name="description" content="Vi ligger p&#xE5; &#xD8;stfyn">'},robots:{status:404,text:''},sitemap:{status:403,text:'denied'},profile:{company:'Frørup',market:'Fyn'}});assert.equal(r.description,'Vi ligger på Østfyn');assert.equal(r.checks.find(c=>c.label==='Virksomheden er identificeret').pass,true);assert.match(r.checks.find(c=>c.label==='Virksomheden er identificeret').evidence,/findes/);assert.equal(r.checks.find(c=>c.label.includes('Geografi')).pass,true);assert.equal(r.checks.find(c=>c.label.includes('Oversigt')).pass,null);});
