#!/usr/bin/env python3
"""Generate detailed Insight product pages in all site languages."""

from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]

locales = {
    "dk": {"html": "da", "products": "produkter.html", "insight": "waltham-insight.html", "back": "← Tilbage til produkter", "family": "Waltham Insight", "contact": "Tal med os om opgaven", "fit": "Passer især til", "delivery": "Det får I", "method": "Sådan arbejder vi", "price": "Vejledende pris", "next": "Næste skridt", "conf": "En kort, fortrolig samtale er nok til at vurdere, om produktet passer til spørgsmålet."},
    "no": {"html": "nb", "products": "produkter.html", "insight": "waltham-insight.html", "back": "← Tilbake til produkter", "family": "Waltham Insight", "contact": "Snakk med oss om oppgaven", "fit": "Passer særlig for", "delivery": "Dette får dere", "method": "Slik arbeider vi", "price": "Veiledende pris", "next": "Neste steg", "conf": "En kort, fortrolig samtale er nok til å vurdere om produktet passer til spørsmålet."},
    "en": {"html": "en", "products": "products.html", "insight": "waltham-insight.html", "back": "← Back to products", "family": "Waltham Insight", "contact": "Discuss the assignment", "fit": "Especially useful for", "delivery": "What you receive", "method": "How we work", "price": "Indicative price", "next": "Next step", "conf": "A short, confidential conversation is enough to assess whether the product fits the question."},
    "de": {"html": "de", "products": "produkte.html", "insight": "waltham-insight.html", "back": "← Zurück zu den Produkten", "family": "Waltham Insight", "contact": "Aufgabe mit uns besprechen", "fit": "Besonders geeignet für", "delivery": "Das erhalten Sie", "method": "So arbeiten wir", "price": "Preisrahmen", "next": "Nächster Schritt", "conf": "Ein kurzes, vertrauliches Gespräch genügt, um zu beurteilen, ob das Produkt zur Fragestellung passt."},
}

products = {
    "insight-discovery": {
        "dk": {"title": "Insight Discovery", "eyebrow": "Research før spørgeskema", "lead": "Fra et åbent spørgsmål til dokumenterede mønstre, muligheder og hypoteser — uden at begynde med en stor undersøgelse.", "promise": "Find det, der allerede kan vides. Afgræns det, der faktisk skal undersøges.", "intro": "AI kan gennemgå langt flere kilder, end et traditionelt projekt normalt tillader. Waltham bruger den kapacitet til at skabe overblik — og erfaring til at skelne mellem et interessant signal og en konklusion, der kan forsvares.", "fit_items": ["Ledelser med et vigtigt, men endnu uklart markedsspørgsmål", "Organisationer, der vil finde nye vinkler eller muligheder", "Redaktioner og kommunikationsfolk, der har brug for en dokumenterbar historie"], "deliver_items": ["Et præcist beslutnings- eller undersøgelsesspørgsmål", "Kildekort med officielle data, eksisterende research og markedssignaler", "Prioriterede mønstre, muligheder og alternative forklaringer", "Anbefaling af det mindste meningsfulde næste skridt"], "steps": [("01", "Afgræns", "Vi gør det åbne spørgsmål undersøgbart."), ("02", "Opdag", "AI kortlægger relevante data, kilder og signaler."), ("03", "Udfordr", "Vi søger både bekræftelse og modbeviser."), ("04", "Konkludér", "I får et klart fund, usikkerheder og næste skridt.")], "price_text": "Pris efter afgrænsning", "price_note": "Omfang og databehov aftales før start."},
        "no": {"title": "Insight Discovery", "eyebrow": "Research før spørreundersøkelse", "lead": "Fra et åpent spørsmål til dokumenterte mønstre, muligheter og hypoteser — uten å begynne med en stor undersøkelse.", "promise": "Finn det som allerede kan vites. Avgrens det som faktisk må undersøkes.", "intro": "AI kan gjennomgå langt flere kilder enn et tradisjonelt prosjekt vanligvis tillater. Waltham bruker kapasiteten til å skape oversikt — og erfaringen til å skille et interessant signal fra en konklusjon som kan forsvares.", "fit_items": ["Ledelser med et viktig, men fortsatt uklart markedsspørsmål", "Organisasjoner som vil finne nye vinkler eller muligheter", "Redaksjoner og kommunikasjonsfolk som trenger en dokumenterbar historie"], "deliver_items": ["Et presist beslutnings- eller undersøkelsesspørsmål", "Kildekart med offisielle data, eksisterende research og markedssignaler", "Prioriterte mønstre, muligheter og alternative forklaringer", "Anbefaling av det minste meningsfulle neste steget"], "steps": [("01", "Avgrens", "Vi gjør det åpne spørsmålet mulig å undersøke."), ("02", "Oppdag", "AI kartlegger relevante data, kilder og signaler."), ("03", "Utfordre", "Vi leter etter både bekreftelse og motbevis."), ("04", "Konkluder", "Dere får tydelige funn, usikkerhet og neste steg.")], "price_text": "Pris etter avgrensning", "price_note": "Omfang og databehov avtales før oppstart."},
        "en": {"title": "Insight Discovery", "eyebrow": "Research before survey", "lead": "From an open question to documented patterns, opportunities and hypotheses — without beginning with a large study.", "promise": "Find what can already be known. Isolate what genuinely needs investigation.", "intro": "AI can review far more sources than a conventional project usually allows. Waltham uses that capacity to create breadth — and experience to distinguish an interesting signal from a conclusion that can be defended.", "fit_items": ["Leadership teams with an important but still unclear market question", "Organisations looking for new angles or opportunities", "Editorial and communications teams needing a documentable story"], "deliver_items": ["A precise decision or research question", "A source map covering official data, existing research and market signals", "Prioritised patterns, opportunities and alternative explanations", "A recommendation for the smallest meaningful next step"], "steps": [("01", "Define", "We turn the open question into something testable."), ("02", "Discover", "AI maps relevant data, sources and signals."), ("03", "Challenge", "We seek both supporting and contradictory evidence."), ("04", "Conclude", "You receive clear findings, uncertainty and next steps.")], "price_text": "Price after scoping", "price_note": "Scope and data needs are agreed before work begins."},
        "de": {"title": "Insight Discovery", "eyebrow": "Recherche vor Befragung", "lead": "Von einer offenen Frage zu dokumentierten Mustern, Chancen und Hypothesen — ohne mit einer großen Studie zu beginnen.", "promise": "Ermitteln, was bereits bekannt sein kann. Eingrenzen, was wirklich untersucht werden muss.", "intro": "KI kann deutlich mehr Quellen prüfen, als ein konventionelles Projekt normalerweise zulässt. Waltham nutzt diese Kapazität für Breite — und Erfahrung, um ein interessantes Signal von einer belastbaren Schlussfolgerung zu unterscheiden.", "fit_items": ["Führungsteams mit einer wichtigen, aber noch unklaren Marktfrage", "Organisationen auf der Suche nach neuen Perspektiven oder Chancen", "Redaktionen und Kommunikationsteams, die eine belegbare Geschichte benötigen"], "deliver_items": ["Eine präzise Entscheidungs- oder Forschungsfrage", "Eine Quellenkarte aus offiziellen Daten, bestehender Forschung und Marktsignalen", "Priorisierte Muster, Chancen und alternative Erklärungen", "Eine Empfehlung für den kleinsten sinnvollen nächsten Schritt"], "steps": [("01", "Eingrenzen", "Wir machen die offene Frage untersuchbar."), ("02", "Entdecken", "KI kartiert relevante Daten, Quellen und Signale."), ("03", "Prüfen", "Wir suchen bestätigende und widersprechende Evidenz."), ("04", "Schließen", "Sie erhalten klare Befunde, Unsicherheiten und nächste Schritte.")], "price_text": "Preis nach Abgrenzung", "price_note": "Umfang und Datenbedarf werden vor Beginn vereinbart."},
    },
    "market-intelligence-sprint": {
        "dk": {"title": "Market Intelligence Sprint", "eyebrow": "Et marked. Ét beslutningsspørgsmål.", "lead": "En koncentreret markedsanalyse af størrelse, kunder, konkurrenter og realistiske muligheder — leveret til en beslutning, ikke til en hylde.", "promise": "Gør et stort markedsspørgsmål lille nok til at handle på.", "intro": "Sprinten kombinerer officielle data, eksisterende analyser, virksomheds- og adfærdssignaler med AI-baseret research. Waltham vurderer kilderne, tester alternative forklaringer og omsætter materialet til en klar prioritering.", "fit_items": ["Virksomheder, der overvejer et nyt marked eller segment", "Ledelser, der skal prioritere mellem flere vækstmuligheder", "Teams, der har brug for et hurtigt, uafhængigt markedsgrundlag"], "deliver_items": ["Estimat af markedets størrelse og udvikling", "Kort over relevante kundegrupper og konkurrenter", "Prioriterede muligheder, barrierer og markedssignaler", "En kort beslutningsrapport og anbefalet handling"], "steps": [("01", "Beslutning", "Vi definerer den konkrete beslutning analysen skal støtte."), ("02", "Marked", "AI samler og strukturerer det relevante kildegrundlag."), ("03", "Realitetstjek", "Vi vurderer kvalitet, huller og alternative forklaringer."), ("04", "Prioritering", "I får de mest realistiske muligheder og næste træk.")], "price_text": "Fra 18.000 DKK", "price_note": "Typisk afgrænset til ét marked og ét centralt spørgsmål."},
        "no": {"title": "Market Intelligence Sprint", "eyebrow": "Ett marked. Ett beslutningsspørsmål.", "lead": "En konsentrert markedsanalyse av størrelse, kunder, konkurrenter og realistiske muligheter — levert for en beslutning, ikke for en hylle.", "promise": "Gjør et stort markedsspørsmål lite nok til å handle på.", "intro": "Sprinten kombinerer offisielle data, eksisterende analyser, virksomhets- og atferdssignaler med AI-basert research. Waltham vurderer kildene, tester alternative forklaringer og gjør materialet om til en tydelig prioritering.", "fit_items": ["Virksomheter som vurderer et nytt marked eller segment", "Ledelser som må prioritere mellom flere vekstmuligheter", "Team som trenger et raskt, uavhengig markedsgrunnlag"], "deliver_items": ["Estimat av markedets størrelse og utvikling", "Kart over relevante kundegrupper og konkurrenter", "Prioriterte muligheter, barrierer og markedssignaler", "En kort beslutningsrapport og anbefalt handling"], "steps": [("01", "Beslutning", "Vi definerer beslutningen analysen skal støtte."), ("02", "Marked", "AI samler og strukturerer det relevante kildegrunnlaget."), ("03", "Realitetssjekk", "Vi vurderer kvalitet, hull og alternative forklaringer."), ("04", "Prioritering", "Dere får de mest realistiske mulighetene og neste trekk.")], "price_text": "Fra 18 000 DKK", "price_note": "Vanligvis avgrenset til ett marked og ett sentralt spørsmål."},
        "en": {"title": "Market Intelligence Sprint", "eyebrow": "One market. One decision question.", "lead": "A concentrated market analysis of size, customers, competitors and realistic opportunities — delivered for a decision, not a shelf.", "promise": "Make a large market question small enough to act on.", "intro": "The sprint combines official data, existing analysis, company and behavioural signals with AI-based research. Waltham assesses the sources, tests alternative explanations and turns the material into a clear priority.", "fit_items": ["Companies considering a new market or segment", "Leadership teams choosing between several growth opportunities", "Teams needing a rapid, independent market foundation"], "deliver_items": ["An estimate of market size and development", "A map of relevant customer groups and competitors", "Prioritised opportunities, barriers and market signals", "A concise decision report and recommended action"], "steps": [("01", "Decision", "We define the decision the analysis must support."), ("02", "Market", "AI gathers and structures the relevant evidence base."), ("03", "Reality check", "We assess quality, gaps and alternative explanations."), ("04", "Priority", "You receive the most realistic opportunities and next moves.")], "price_text": "From DKK 18,000", "price_note": "Usually scoped to one market and one central question."},
        "de": {"title": "Market Intelligence Sprint", "eyebrow": "Ein Markt. Eine Entscheidungsfrage.", "lead": "Eine konzentrierte Marktanalyse zu Größe, Kunden, Wettbewerbern und realistischen Chancen — für eine Entscheidung, nicht für das Archiv.", "promise": "Eine große Marktfrage so konkret machen, dass Handeln möglich wird.", "intro": "Der Sprint verbindet offizielle Daten, bestehende Analysen sowie Unternehmens- und Verhaltenssignale mit KI-gestützter Recherche. Waltham bewertet die Quellen, prüft alternative Erklärungen und übersetzt das Material in klare Prioritäten.", "fit_items": ["Unternehmen, die einen neuen Markt oder ein Segment erwägen", "Führungsteams, die zwischen mehreren Wachstumschancen wählen", "Teams, die schnell eine unabhängige Marktgrundlage benötigen"], "deliver_items": ["Eine Schätzung von Marktgröße und Entwicklung", "Eine Karte relevanter Kundengruppen und Wettbewerber", "Priorisierte Chancen, Barrieren und Marktsignale", "Einen kompakten Entscheidungsbericht mit Handlungsempfehlung"], "steps": [("01", "Entscheidung", "Wir definieren die Entscheidung, die die Analyse unterstützen soll."), ("02", "Markt", "KI sammelt und strukturiert die relevante Evidenzbasis."), ("03", "Realitätscheck", "Wir bewerten Qualität, Lücken und alternative Erklärungen."), ("04", "Priorität", "Sie erhalten die realistischsten Chancen und nächsten Schritte.")], "price_text": "Ab 18.000 DKK", "price_note": "Üblicherweise auf einen Markt und eine zentrale Frage begrenzt."},
    },
}

def list_items(items):
    return "".join(f"<li>{item}</li>" for item in items)

for slug, translations in products.items():
    for lang, shared in locales.items():
        p = translations[lang]
        subject = quote(f"Waltham Insight | {p['title']}")
        steps = "".join(f'<article><b>{n}</b><h3>{title}</h3><p>{text}</p></article>' for n, title, text in p["steps"])
        page = f'''<!doctype html><html lang="{shared['html']}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{p['lead']}"><title>{p['title']} — Waltham Insight</title><link rel="stylesheet" href="../css/styles.css"><link rel="stylesheet" href="../css/insight-product.css"><link rel="stylesheet" href="../css/brand-logo.css"></head><body class="insight-product-page"><header class="product-detail-nav"><div class="wrap"><a class="logo" href="index.html">Waltham<span>.</span><small>Insight</small></a><a href="{shared['products']}#insight">{shared['back']}</a></div></header><main><section class="product-detail-hero"><div class="wrap"><p class="eyebrow">{shared['family']} · {p['eyebrow']}</p><h1>{p['title']}</h1><p class="lead">{p['lead']}</p><a class="button primary" href="#contact">{shared['contact']}</a></div></section><section class="product-detail-intro wrap"><h2>{p['promise']}</h2><p>{p['intro']}</p></section><section class="product-detail-pairs wrap"><article><p class="label">{shared['fit']}</p><ul>{list_items(p['fit_items'])}</ul></article><article><p class="label">{shared['delivery']}</p><ul>{list_items(p['deliver_items'])}</ul></article></section><section class="product-detail-method"><div class="wrap"><p class="label">{shared['method']}</p><div class="product-detail-steps">{steps}</div></div></section><section class="product-detail-price wrap"><div><p class="label">{shared['price']}</p><h2>{p['price_text']}</h2><p>{p['price_note']}</p></div><div id="contact"><p class="label">{shared['next']}</p><p>{shared['conf']}</p><a class="button primary" href="mailto:waltham@me.com?subject={subject}">{shared['contact']}</a></div></section></main><footer><div class="wrap"><a href="{shared['insight']}">{shared['family']} →</a><a href="{shared['products']}#insight">{shared['back'].replace('← ', '')}</a></div></footer><script src="/js/cookie-notice.js"></script></body></html>'''
        (ROOT / lang / f"{slug}.html").write_text(page, encoding="utf-8")

sitemap = ROOT / "sitemap.xml"
xml = sitemap.read_text(encoding="utf-8")
for slug in products:
    for lang in locales:
        domain = "waltham.no" if lang == "no" else "waltham.dk"
        url = f"https://{domain}/{lang}/{slug}.html"
        if url not in xml:
            xml = xml.replace("</urlset>", f"  <url><loc>{url}</loc></url>\n</urlset>")
sitemap.write_text(xml, encoding="utf-8")
