from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
DATA={
"dk":("Erfaringsfordelen","50+ er ikke en restgruppe. Det kan være den næste bølge af venturebyggere.","OECD viser, at beskæftigelsen blandt 55–64-årige på tværs af medlemslandene steg fra 47,7 procent i 2004 til 66,4 procent i 2024. Erfarne mennesker er mere aktive på arbejdsmarkedet end før — samtidig med at AI sænker tærsklen for at omsætte viden til digitale løsninger.","Værdien ligger ikke i, at erfaring erstatter tekniske kompetencer. Den ligger i kombinationen: relationer, situationsforståelse, troværdighed og mønstergenkendelse kan nu arbejde sammen med værktøjer, der gør research, produktion og lancering langt mere tilgængelig.","Et længere arbejdsliv kan blive et mere skabende arbejdsliv.","OECD · Pensions at a Glance 2025"),
"no":("Erfaringsfordelen","50+ er ikke en restgruppe. Det kan være den neste bølgen av venturebyggere.","OECD viser at sysselsettingen blant 55–64-åringer på tvers av medlemslandene steg fra 47,7 prosent i 2004 til 66,4 prosent i 2024. Erfarne mennesker er mer aktive i arbeidsmarkedet enn før — samtidig som AI senker terskelen for å omsette kunnskap til digitale løsninger.","Verdien ligger ikke i at erfaring erstatter teknisk kompetanse. Den ligger i kombinasjonen: relasjoner, situasjonsforståelse, troverdighet og mønstergjenkjenning kan nå arbeide sammen med verktøy som gjør research, produksjon og lansering langt mer tilgjengelig.","Et lengre arbeidsliv kan bli et mer skapende arbeidsliv.","OECD · Pensions at a Glance 2025"),
"en":("The experience advantage","The over-50s are not a residual group. They may be the next wave of venture builders.","OECD data show that employment among 55–64-year-olds across member countries rose from 47.7 per cent in 2004 to 66.4 per cent in 2024. Experienced people are more active in the labour market than before — while AI lowers the threshold for turning knowledge into digital solutions.","The value is not that experience replaces technical skill. It lies in the combination: relationships, situational understanding, credibility and pattern recognition can now work with tools that make research, production and launch far more accessible.","A longer working life can become a more creative working life.","OECD · Pensions at a Glance 2025"),
"de":("Der Erfahrungsvorteil","Menschen über 50 sind keine Restgruppe. Sie könnten die nächste Welle von Venture-Gründern sein.","OECD-Daten zeigen, dass die Beschäftigung der 55- bis 64-Jährigen in den Mitgliedsländern von 47,7 Prozent im Jahr 2004 auf 66,4 Prozent im Jahr 2024 stieg. Erfahrene Menschen sind aktiver am Arbeitsmarkt als früher — während KI die Hürde senkt, Wissen in digitale Lösungen zu übersetzen.","Der Wert liegt nicht darin, dass Erfahrung technische Kompetenz ersetzt. Er liegt in der Kombination: Beziehungen, Situationsverständnis, Glaubwürdigkeit und Mustererkennung können mit Werkzeugen arbeiten, die Recherche, Produktion und Markteinführung deutlich zugänglicher machen.","Ein längeres Arbeitsleben kann ein kreativeres Arbeitsleben werden.","OECD · Pensions at a Glance 2025")}

for code,t in DATA.items():
    label,title,data,meaning,quote,source=t
    block=f'<section class="section experience-advantage"><div class="wrap"><div class="experience-head"><div><p class="label">{label}</p><h2>{title}</h2></div><div class="copy"><p>{data}</p><p>{meaning}</p><a class="experience-source" href="https://www.oecd.org/en/publications/pensions-at-a-glance-2025_e40274c1-en/full-report/changes-in-employment-rates-of-older-workers_b7554479.html" target="_blank" rel="noopener noreferrer">{source} →</a></div></div><p class="experience-manifesto">{quote}</p></div></section>'
    path=ROOT/code/'waltham-ventures.html'
    html=path.read_text(encoding='utf-8')
    if 'experience-advantage' not in html:
        html=html.replace('<section class="section venture-collaboration">',block+'<section class="section venture-collaboration">',1)
    path.write_text(html,encoding='utf-8')
