from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DATA = {
"dk": dict(label="Samarbejdsmodel under udvikling", title="Erfaring skal ikke pensioneres, bare fordi teknologien ændrer sig.", lead="Mange erfarne, uafhængige mennesker har stærke netværk, god forretningsforståelse og stadig lyst til at skabe noget. Waltham vil undersøge en samarbejdsmodel, hvor den erfaring kan møde fælles, hurtige metoder til research, markedstest, produktion og lancering.", guard="Det skal ikke være et løst netværk eller en bevægelse bygget på store ord. Det skal være et kurateret arbejdsfællesskab omkring konkrete muligheder, tydelige roller og fair økonomi.", bring="Partneren bringer", bring_items=["Brancheindsigt og praktisk erfaring","Et relevant netværk og adgang til markedet","En idé, kundeudfordring eller konkret mulighed"], platform="Waltham bringer", platform_items=["Hurtig research og markedsverifikation","Positionering, digital produktion og første lancering","En genanvendelig metode til at lære hurtigt"], rules="Før vi bygger", rules_items=["Aftal ejerskab, roller, omkostninger og mulig indtjening","Definér den mindste test og et tydeligt stopkriterium","Del læringen — også når testen viser, at vi skal stoppe"], principle="Test småt. Lær hurtigt. Byg videre, når markedet svarer. Slip det ordentligt, når det ikke gør.", future="Målet er ikke blot at overleve en fremtid med AI. Det er at give erfarne mennesker en praktisk måde at forblive aktive, relevante og værdiskabende i den.", cta="Interesseret i venture-netværket?"),
"no": dict(label="Samarbeidsmodell under utvikling", title="Erfaring skal ikke pensjoneres bare fordi teknologien endrer seg.", lead="Mange erfarne og uavhengige mennesker har sterke nettverk, god forretningsforståelse og fortsatt lyst til å skape noe. Waltham vil undersøke en samarbeidsmodell der erfaringen kan møte felles, raske metoder for research, markedstest, produksjon og lansering.", guard="Det skal ikke være et løst nettverk eller en bevegelse bygget på store ord. Det skal være et kuratert arbeidsfellesskap rundt konkrete muligheter, tydelige roller og rettferdig økonomi.", bring="Partneren bringer", bring_items=["Bransjeinnsikt og praktisk erfaring","Et relevant nettverk og tilgang til markedet","En idé, kundeutfordring eller konkret mulighet"], platform="Waltham bringer", platform_items=["Rask research og markedsverifisering","Posisjonering, digital produksjon og første lansering","En gjenbrukbar metode for å lære raskt"], rules="Før vi bygger", rules_items=["Avtal eierskap, roller, kostnader og mulig inntjening","Definer den minste testen og et tydelig stoppkriterium","Del læringen — også når testen viser at vi bør stoppe"], principle="Test smått. Lær raskt. Bygg videre når markedet svarer. Slipp det ordentlig når det ikke gjør det.", future="Målet er ikke bare å overleve en fremtid med AI. Det er å gi erfarne mennesker en praktisk måte å forbli aktive, relevante og verdiskapende i den.", cta="Interessert i venture-nettverket?"),
"en": dict(label="Collaboration model in development", title="Experience should not retire simply because technology changes.", lead="Many experienced, independent people have strong networks, sound commercial judgement and a continuing desire to create. Waltham wants to explore a model where that experience meets shared, rapid methods for research, market testing, production and launch.", guard="This should not be a loose network or a movement built on grand claims. It should be a curated working community around concrete opportunities, clear roles and fair economics.", bring="The partner brings", bring_items=["Sector insight and practical experience","A relevant network and access to the market","An idea, customer problem or concrete opportunity"], platform="Waltham brings", platform_items=["Rapid research and market verification","Positioning, digital production and first launch","A reusable method for learning quickly"], rules="Before we build", rules_items=["Agree ownership, roles, costs and potential revenue","Define the smallest test and a clear stopping rule","Share the learning — including when the test tells us to stop"], principle="Test small. Learn fast. Build further when the market responds. Let go properly when it does not.", future="The objective is not merely to survive an AI-shaped future. It is to give experienced people a practical way to remain active, relevant and value-creating within it.", cta="Interested in the venture network?"),
"de": dict(label="Kooperationsmodell in Entwicklung", title="Erfahrung sollte nicht in Rente gehen, nur weil sich Technologie verändert.", lead="Viele erfahrene, unabhängige Menschen verfügen über starke Netzwerke, kaufmännisches Urteilsvermögen und weiterhin Lust, etwas zu schaffen. Waltham möchte ein Modell untersuchen, in dem diese Erfahrung auf gemeinsame, schnelle Methoden für Recherche, Markttest, Produktion und Start trifft.", guard="Es soll kein loses Netzwerk und keine Bewegung mit großen Behauptungen sein. Es soll eine kuratierte Arbeitsgemeinschaft rund um konkrete Chancen, klare Rollen und faire wirtschaftliche Regeln sein.", bring="Der Partner bringt", bring_items=["Branchenwissen und praktische Erfahrung","Ein relevantes Netzwerk und Marktzugang","Eine Idee, Kundenherausforderung oder konkrete Chance"], platform="Waltham bringt", platform_items=["Schnelle Recherche und Marktverifizierung","Positionierung, digitale Produktion und ersten Start","Eine wiederverwendbare Methode für schnelles Lernen"], rules="Bevor wir bauen", rules_items=["Eigentum, Rollen, Kosten und mögliche Erlöse vereinbaren","Den kleinsten Test und ein klares Abbruchkriterium definieren","Lernen teilen — auch wenn der Test zum Stopp rät"], principle="Klein testen. Schnell lernen. Weiterbauen, wenn der Markt antwortet. Sauber loslassen, wenn er es nicht tut.", future="Ziel ist nicht nur, eine von KI geprägte Zukunft zu überleben. Erfahrene Menschen sollen darin praktisch aktiv, relevant und wertschöpfend bleiben können.", cta="Interesse am Venture-Netzwerk?")}

def render(t):
    def card(title,items): return f'<article><h3>{title}</h3><ul>'+''.join(f'<li>{x}</li>' for x in items)+'</ul></article>'
    cards=card(t['bring'],t['bring_items'])+card(t['platform'],t['platform_items'])+card(t['rules'],t['rules_items'])
    return f'<section class="section venture-collaboration"><div class="wrap"><div class="collaboration-head"><div><p class="label">{t["label"]}</p><h2>{t["title"]}</h2></div><div class="copy"><p>{t["lead"]}</p><p>{t["guard"]}</p></div></div><div class="collaboration-cards">{cards}</div><blockquote class="collaboration-principle">{t["principle"]}</blockquote><div class="collaboration-future"><p>{t["future"]}</p><a class="button primary" href="mailto:waltham@me.com?subject=Waltham%20venture-netværk">{t["cta"]}</a></div></div></section>'

for code,t in DATA.items():
    path=ROOT/code/'waltham-ventures.html'
    html=path.read_text(encoding='utf-8')
    if 'venture-collaboration' not in html:
        html=html.replace('<section class="section venture-urgency">',render(t)+'<section class="section venture-urgency">',1)
    path.write_text(html,encoding='utf-8')
